Repository BinaryStudioAcademy/bsa-2020-knewless, pull requests merged in 2020-08, with the labels that each got.

#2 Added migrations - created database structure and added test data
  backend/core/src/main/resources/db/migration/.keep
  backend/core/src/main/resources/db/migration/V1__create_db_structure.sql
  backend/core/src/main/resources/db/migration/V2__seed_data.sql
Labels: enhancement

#5 Added base entities and folder structure
  backend/core/src/main/java/com/knewless/core/achievement/AchievementRepository.java
  backend/core/src/main/java/com/knewless/core/achievement/model/Achievement.java
  backend/core/src/main/java/com/knewless/core/achievement/model/AchievementType.java
  backend/core/src/main/java/com/knewless/core/article/ArticleRepository.java
  backend/core/src/main/java/com/knewless/core/article/articleComment/ArticleCommentRepository.java
  backend/core/src/main/java/com/knewless/core/article/articleComment/model/ArticleComment.java
  backend/core/src/main/java/com/knewless/core/article/articleReaction/ArticleReactionRepository.java
  backend/core/src/main/java/com/knewless/core/article/articleReaction/model/ArticleReaction.java
  backend/core/src/main/java/com/knewless/core/article/model/Article.java
  backend/core/src/main/java/com/knewless/core/author/AuthorRepository.java
  backend/core/src/main/java/com/knewless/core/author/model/Author.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/courseComment/CourseCommentRepository.java
  backend/core/src/main/java/com/knewless/core/course/courseComment/model/CourseComment.java
  backend/core/src/main/java/com/knewless/core/course/courseReaction/CourseReactionRepository.java
  backend/core/src/main/java/com/knewless/core/course/courseReaction/model/CourseReaction.java
  backend/core/src/main/java/com/knewless/core/course/model/Course.java
  backend/core/src/main/java/com/knewless/core/currentUserCource/CurrentUserCourseRepository.java
  backend/core/src/main/java/com/knewless/core/currentUserCource/model/CurrentUserCourse.java
  backend/core/src/main/java/com/knewless/core/data/DataController.java
  backend/core/src/main/java/com/knewless/core/data/DataRepository.java
  backend/core/src/main/java/com/knewless/core/data/DataService.java
  backend/core/src/main/java/com/knewless/core/data/dto/DataDto.java
  backend/core/src/main/java/com/knewless/core/db/BaseComment.java
  backend/core/src/main/java/com/knewless/core/db/BaseEntity.java
  backend/core/src/main/java/com/knewless/core/db/BaseReaction.java
  backend/core/src/main/java/com/knewless/core/db/SourceType.java
  backend/core/src/main/java/com/knewless/core/favorite/FavoriteRepository.java
  backend/core/src/main/java/com/knewless/core/favorite/model/Favorite.java
  backend/core/src/main/java/com/knewless/core/history/HistoryRepository.java
  backend/core/src/main/java/com/knewless/core/history/model/History.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureRepository.java
  backend/core/src/main/java/com/knewless/core/lecture/homework/HomeworkRepository.java
  backend/core/src/main/java/com/knewless/core/lecture/homework/model/Homework.java
  backend/core/src/main/java/com/knewless/core/lecture/lectureComment/LectureCommentRepository.java
  backend/core/src/main/java/com/knewless/core/lecture/lectureComment/model/LectureComment.java
  backend/core/src/main/java/com/knewless/core/lecture/lectureReaction/LectureReactionRepository.java
  backend/core/src/main/java/com/knewless/core/lecture/lectureReaction/model/LectureReaction.java
  backend/core/src/main/java/com/knewless/core/lecture/model/Lecture.java
  backend/core/src/main/java/com/knewless/core/notification/NotificationRepository.java
  backend/core/src/main/java/com/knewless/core/notification/model/Notification.java
  backend/core/src/main/java/com/knewless/core/path/PathRepository.java
  backend/core/src/main/java/com/knewless/core/path/model/Path.java
  backend/core/src/main/java/com/knewless/core/school/SchoolRepository.java
  backend/core/src/main/java/com/knewless/core/school/model/School.java
  backend/core/src/main/java/com/knewless/core/student/StudentRepository.java
  backend/core/src/main/java/com/knewless/core/student/model/Student.java
  backend/core/src/main/java/com/knewless/core/subscription/SubscriptionRepository.java
  backend/core/src/main/java/com/knewless/core/subscription/model/Subscription.java
  backend/core/src/main/java/com/knewless/core/tag/TagRepository.java
  backend/core/src/main/java/com/knewless/core/tag/model/Tag.java
  backend/core/src/main/java/com/knewless/core/user/UserController.java
  backend/core/src/main/java/com/knewless/core/user/UserRepository.java
  backend/core/src/main/java/com/knewless/core/user/UserService.java
  backend/core/src/main/java/com/knewless/core/user/model/User.java
  backend/core/src/main/java/com/knewless/core/user/role/RoleRepository.java
  backend/core/src/main/java/com/knewless/core/user/role/model/Role.java
  backend/core/src/main/java/com/knewless/core/user/role/model/RoleType.java
Labels: enhancement

#13 Patch/6 Landing
  frontend/src/helpers/path.helper.ts
  frontend/src/screens/Landing/containers/LandingPage/styles.module.sass
Labels: patch

#16 Patch/6 Landing. Opacity percents to float
  frontend/src/components/CourseCard/rating.sass
Labels: patch

#18 Patch/6 landing
  frontend/src/components/CardsSegment/styles.module.sass
  frontend/src/components/PathCard/styles.module.sass
  frontend/src/screens/Landing/containers/LandingPage/index.tsx
  frontend/src/screens/Landing/services/mock.ts
  frontend/src/styles/common.sass
Labels: patch

#30 Hotfix/author main page global styles
  frontend/src/screens/AuthorMainPage/components/AuthorCardsSegment/styles.module.sass
  frontend/src/screens/AuthorMainPage/components/AuthorOptionsDropdown/styles.module.sass
  frontend/src/screens/AuthorMainPage/containers/MainPage/styles.module.sass
Labels: bug

#31 Hotfix/author followers and paths
  backend/core/src/main/java/com/knewless/core/author/mapper/AuthorInfoMapper.java
  backend/core/src/main/java/com/knewless/core/author/model/Author.java
  backend/core/src/main/java/com/knewless/core/path/PathController.java
  backend/core/src/main/java/com/knewless/core/path/PathRepository.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
Labels: bug

#33 Patch/31 author main page ui
  frontend/src/screens/AuthorMainPage/components/AuthorCardsSegment/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorCardsSegment/styles.module.sass
  frontend/src/screens/AuthorMainPage/components/AuthorCourseCard/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorOptionsDropdown/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorOptionsDropdown/styles.module.sass
  frontend/src/screens/AuthorMainPage/components/AuthorPathCard/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorPathCard/styles.module.sass
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
  frontend/src/screens/AuthorMainPage/containers/MainPage/styles.module.sass
Labels: patch

#26 Feature/28 lecture page
  backend/core/src/main/java/com/knewless/core/author/AuthorRepository.java
  backend/core/src/main/java/com/knewless/core/author/dto/AuthorNameIdProjection.java
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseIdByLectureIdProjection.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseToPlayerDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseToPlayerProjection.java
  backend/core/src/main/java/com/knewless/core/course/model/Course.java
  backend/core/src/main/java/com/knewless/core/lecture/dto/LectureToPlayerDto.java
  backend/core/src/main/java/com/knewless/core/notification/NotificationRepository.java
  backend/core/src/main/java/com/knewless/core/path/model/Path.java
  backend/core/src/main/resources/db/migration/V9_add_more_lectures.sql
  frontend/package.json
  frontend/src/containers/Routing/index.tsx
  frontend/src/reducers/index.ts
  frontend/src/sagas/index.ts
  frontend/src/screens/LecturePage/containers/Lectures/index.tsx
  frontend/src/screens/LecturePage/containers/Lectures/lecturesList.tsx
  frontend/src/screens/LecturePage/containers/Lectures/lecturesMenu.tsx
  frontend/src/screens/LecturePage/containers/Lectures/reducers.tsx
  frontend/src/screens/LecturePage/containers/Lectures/sagas.tsx
  frontend/src/screens/LecturePage/containers/Lectures/styles.sass
  frontend/src/screens/LecturePage/models/CourseData.tsx
  frontend/src/screens/LecturePage/models/IAuthor.tsx
  frontend/src/screens/LecturePage/models/ICourse.tsx
  frontend/src/screens/LecturePage/models/ILectures.tsx
  frontend/src/screens/LecturePage/models/ILecturesList.tsx
  frontend/src/screens/LecturePage/models/ILecturesMenu.tsx
  frontend/src/screens/LecturePage/reducers/index.tsx
  frontend/src/screens/LecturePage/routines/index.tsx
  frontend/src/screens/LecturePage/sagas/index.tsx
  frontend/src/screens/LecturePage/services/lectures.api.tsx
Labels: enhancement

#35 Patch/31 author main page backend
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseMapper.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/model/Course.java
  backend/core/src/main/java/com/knewless/core/path/PathController.java
  backend/core/src/main/java/com/knewless/core/path/PathRepository.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  frontend/src/sagas/index.ts
  frontend/src/screens/AuthorMainPage/components/AuthorCourseCard/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorCourseCard/styles.module.sass
  frontend/src/screens/AuthorMainPage/components/AuthorInfoBlock/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorOptionsDropdown/styles.module.sass
  frontend/src/screens/AuthorMainPage/components/AuthorPathCard/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorPathCard/styles.module.sass
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
  frontend/src/screens/AuthorMainPage/containers/MainPage/reducer.ts
  frontend/src/screens/AuthorMainPage/containers/MainPage/sagas.ts
  frontend/src/screens/AuthorMainPage/models/IAuthorMainPageData.ts
  frontend/src/screens/AuthorMainPage/models/IAuthorMainPageState.ts
  frontend/src/screens/AuthorMainPage/reducers/index.ts
  frontend/src/screens/AuthorMainPage/routines/index.ts
  frontend/src/screens/AuthorMainPage/services/author.main.page.service.ts
  frontend/src/screens/AuthorMainPage/services/author.page.mock.ts
Labels: patch

#39 Patch/31 author main page refactor
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseMapper.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/AuthorCourseDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/AuthorCourseQueryResult.java
  backend/core/src/main/java/com/knewless/core/path/PathController.java
  backend/core/src/main/java/com/knewless/core/path/PathMapper.java
  backend/core/src/main/java/com/knewless/core/path/PathRepository.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  backend/core/src/main/java/com/knewless/core/path/dto/AuthorPathDto.java
  backend/core/src/main/java/com/knewless/core/path/dto/AuthorPathQueryResult.java
  frontend/src/screens/AuthorMainPage/components/AuthorCourseCard/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorCourseCard/styles.module.sass
  frontend/src/screens/AuthorMainPage/components/AuthorPathCard/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorPathCard/styles.module.sass
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
  frontend/src/screens/AuthorMainPage/models/IAuthorMainPageData.ts
Labels: patch

#43 Feature/54 swagger
  backend/core/build.gradle
  backend/core/src/main/java/com/knewless/core/security/SecurityConfiguration.java
  backend/core/src/main/java/com/knewless/core/swagger/SwaggerConfiguration.java
Labels: enhancement

#47 Now items are not displayed until loading finishes
  frontend/src/screens/Landing/containers/LandingPage/index.tsx
Labels: patch

#45 Feature/34 page add path
  backend/core/build.gradle
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseResponseDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseWithMinutesProjection.java
  backend/core/src/main/java/com/knewless/core/course/model/Course.java
  backend/core/src/main/java/com/knewless/core/lecture/model/Lecture.java
  backend/core/src/main/java/com/knewless/core/path/PathController.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathCreationRequestDto.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathResponseDto.java
  backend/core/src/main/java/com/knewless/core/path/model/Path.java
  backend/core/src/main/java/com/knewless/core/tag/TagController.java
  backend/core/src/main/java/com/knewless/core/tag/TagMapper.java
  backend/core/src/main/java/com/knewless/core/tag/TagService.java
  backend/core/src/main/java/com/knewless/core/tag/dto/TagDto.java
  backend/core/src/main/java/com/knewless/core/tag/model/Tag.java
  backend/core/src/main/resources/db/migration/V12__paths_tags_courses.sql
  frontend/src/assets/images/no_image.png
  frontend/src/components/CourseCard/index.tsx
  frontend/src/components/CourseCard/styles.module.sass
  frontend/src/components/DependenciesSelector/index.tsx
  frontend/src/components/DependenciesSelector/styles.module.sass
  frontend/src/components/FilterableList/styles.module.sass
  frontend/src/components/PathCard/helper.ts
  frontend/src/components/PathCard/index.tsx
  frontend/src/components/PathCard/styles.module.sass
  frontend/src/components/TagSelector/react_tags.sass
  frontend/src/containers/Routing/index.tsx
  frontend/src/models/AppState.ts
  frontend/src/reducers/index.ts
  frontend/src/sagas/index.ts
  frontend/src/screens/AddCourse/components/LectureComponent/index.tsx
  frontend/src/screens/AddCourse/components/LectureComponent/styles.module.sass
  frontend/src/screens/AddCourse/components/shared/Pull/index.tsx
  frontend/src/screens/AddCourse/components/shared/Pull/styles.module.sass
  frontend/src/screens/AddCourse/components/shared/Selected/index.tsx
  frontend/src/screens/AddCourse/components/shared/element/index.tsx
  frontend/src/screens/AddCourse/components/shared/service.ts
  frontend/src/screens/AddCourse/components/shared/sharedInterface/IItem.ts
  frontend/src/screens/AddCourse/models/ILecture.ts
  frontend/src/screens/AddPath/components/ClickableCourseCard/index.tsx
  frontend/src/screens/AddPath/components/ClickableCourseCard/styles.module.sass
  frontend/src/screens/AddPath/components/PathPreview/index.tsx
  frontend/src/screens/AddPath/components/PathPreview/styles.module.sass
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/react_tags.sass
  frontend/src/screens/AddPath/containers/AddPathPage/reducer.ts
  frontend/src/screens/AddPath/containers/AddPathPage/sagas.ts
  frontend/src/screens/AddPath/containers/AddPathPage/styles.module.sass
  frontend/src/screens/AddPath/models/AddPathData.ts
  frontend/src/screens/AddPath/models/AddPathState.ts
  frontend/src/screens/AddPath/models/domain.ts
  frontend/src/screens/AddPath/reducers/index.ts
  frontend/src/screens/AddPath/routines/index.ts
  frontend/src/screens/AddPath/services/add_page.service.ts
  frontend/src/screens/AddPath/services/landing.service.ts
  frontend/src/screens/AuthorSettings/containers/Settings/styles.module.sass
  frontend/src/styles/common.sass
Labels: enhancement

#44 Feature/65 socket io
  .docker/docker-compose.dev.yml
  .docker/docker-compose.yml
  .docker/nginx/nginx.conf
  .docker/push.Dockerfile
  .env.example/client.env
  .env.example/push.env
  backend/core/src/main/java/com/knewless/core/CoreApplication.java
  backend/core/src/main/java/com/knewless/core/course/model/Course.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureService.java
  backend/core/src/main/java/com/knewless/core/messaging/MessageSender.java
  backend/core/src/main/java/com/knewless/core/messaging/RabbitConfiguration.java
  backend/core/src/main/java/com/knewless/core/messaging/userMessage/UserMessage.java
  backend/core/src/main/java/com/knewless/core/messaging/userMessage/UserMessageType.java
  backend/core/src/main/java/com/knewless/core/notification/dto/NotificationDto.java
  backend/core/src/main/java/com/knewless/core/notification/model/Notification.java
  backend/core/src/main/java/com/knewless/core/websocket/ActiveUserManager.java
  backend/core/src/main/java/com/knewless/core/websocket/SocketUser.java
  backend/core/src/main/java/com/knewless/core/websocket/UserInterceptor.java
  backend/core/src/main/java/com/knewless/core/websocket/WebSocketConfig.java
  backend/core/src/main/java/com/knewless/core/websocket/WebSocketConnectionController.java
  backend/core/src/main/resources/application.properties
  backend/core/src/main/resources/db/migration/V12__delete_collumns_in _notifications.sql
  backend/core/src/test/resources/application.properties
  backend/fileprocessor/src/main/java/fileprocessor/messaging/MessageReceiver.java
  backend/fileprocessor/src/main/java/fileprocessor/messaging/RabbitConfiguration.java
  backend/push/env.ts
  backend/push/package.json
  backend/push/server.ts
  backend/push/src/api/app.ts
  backend/push/src/auth/auth.ts
  backend/push/src/common/utils/path.helper.ts
  backend/push/src/data/dtos/NotificationBody.ts
  backend/push/src/data/dtos/NotificationDTO.ts
  backend/push/src/data/enums/NotificationType.ts
  backend/push/src/rabbitmq/queue.handlers.ts
  backend/push/src/rabbitmq/queue.service.ts
  backend/push/src/websockets/socket.service.ts
  backend/push/tsconfig.json
  frontend/nginx/nginx.conf
  frontend/src/assets/images/giphy.gif
  frontend/src/components/Header/UserElement/index.tsx
  frontend/src/components/WebSocketNotifications/index.tsx
  frontend/src/components/WebSocketNotifications/reducer.ts
  frontend/src/components/WebSocketNotifications/routines.ts
  frontend/src/components/WebSocketNotifications/sagas.ts
  frontend/src/components/WebSocketNotifications/service.ts
  frontend/src/containers/Notifications/NotificatonItem/index.tsx
  frontend/src/containers/Notifications/NotificatonItem/styles.module.sass
  frontend/src/containers/Notifications/index.tsx
  frontend/src/containers/Notifications/model/INotification.ts
  frontend/src/containers/Notifications/reducer.ts
  frontend/src/containers/Notifications/styles.module.sass
  frontend/src/containers/Routing/index.tsx
  frontend/src/containers/WebSocketNotifications/index.tsx
  frontend/src/reducers/index.ts
  frontend/src/sagas/index.ts
  frontend/src/setupProxy.js
  scripts/build.sh
  scripts/deploy.sh
Labels: enhancement

#54 Hotfix/author school image
  frontend/src/screens/AuthorMainPage/containers/MainPage/styles.module.sass
Labels: bug

#58 Feature/7 oauth2
  backend/core/src/main/java/com/knewless/core/auth/AuthController.java
  backend/core/src/main/java/com/knewless/core/auth/AuthService.java
  backend/core/src/main/java/com/knewless/core/security/config/AppProperties.java
  backend/core/src/main/java/com/knewless/core/security/model/AuthResponse.java
  backend/core/src/main/java/com/knewless/core/security/model/RefreshTokenResponse.java
  backend/core/src/main/java/com/knewless/core/security/oauth/TokenProvider.java
  backend/core/src/main/java/com/knewless/core/security/oauth/oauth2/OAuth2AuthenticationSuccessHandler.java
  backend/core/src/main/resources/application.yml
  frontend/src/components/OAuth2RedirectHandler/OAuth2RedirectHandler.tsx
  frontend/src/containers/AppRouter/index.tsx
  frontend/src/helpers/api.helper.ts
  frontend/src/screens/Authentication/constants.tsx
  frontend/src/screens/Authentication/containers/LoginPage/index.tsx
  frontend/src/screens/Authentication/containers/sagas.tsx
  frontend/src/services/auth.service.ts
Labels: enhancement

#62 Fix/10 header
  frontend/src/components/Header/LoginRegister/index.tsx
  frontend/src/components/Header/PopupMenu/index.tsx
  frontend/src/components/Header/UserElement/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/styles.module.sass
  frontend/src/containers/AppRouter/index.tsx
  frontend/src/containers/AppRouter/sagas.ts
  frontend/src/containers/Routing/index.tsx
Labels: patch

#63 Hotfix/swagger host
  .env.example/api.env
  backend/core/src/main/java/com/knewless/core/swagger/SwaggerConfiguration.java
  backend/core/src/main/resources/application.properties
  backend/core/src/test/resources/application.properties
Labels: bug

#53 Role based main page routing
  frontend/src/containers/MainPageRoute/index.tsx
  frontend/src/containers/Routing/index.tsx
Labels: patch

#57 Feature/62 Landing Page wired with the real data
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseMapper.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/path/PathController.java
  backend/core/src/main/java/com/knewless/core/path/PathRepository.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathQueryResult.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathResponseDto.java
  backend/core/src/main/java/com/knewless/core/path/model/Path.java
  backend/core/src/main/resources/db/migration/V14__removed_image_from_paths.sql
  frontend/src/containers/Routing/index.tsx
  frontend/src/screens/Landing/containers/LandingPage/index.tsx
  frontend/src/screens/Landing/containers/LandingPage/sagas.ts
  frontend/src/screens/Landing/services/landing.service.ts
Labels: enhancement

#65 Hotfix/mail already registered message
  backend/core/src/main/java/com/knewless/core/auth/AuthController.java
  backend/core/src/main/java/com/knewless/core/auth/AuthService.java
  backend/core/src/main/java/com/knewless/core/exception/BadRequestException.java
  backend/core/src/main/java/com/knewless/core/security/oauth/oauth2/OAuth2AuthenticationSuccessHandler.java
  frontend/src/screens/Authentication/containers/RegisterPage/index.tsx
  frontend/src/screens/Authentication/containers/sagas.tsx
Labels: bug

#68 Patch/34 Changed styles of AddPath page
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  frontend/src/components/CourseCard/index.tsx
  frontend/src/components/CourseCard/styles.module.sass
  frontend/src/components/DependenciesSelector/index.tsx
  frontend/src/components/LoginForm/styles.module.sass
  frontend/src/components/StyledRating/index.tsx
  frontend/src/components/StyledRating/rating.sass
  frontend/src/components/StyledRating/styles.module.sass
  frontend/src/components/buttons/common.variables.sass
  frontend/src/screens/AddPath/components/ClickableCourseCard/index.tsx
  frontend/src/screens/AddPath/components/ClickableCourseCard/styles.module.sass
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/styles.module.sass
Labels: enhancement, patch

#67 Fix/10 header
  frontend/src/components/AuthImage/styles.module.sass
  frontend/src/containers/Routing/index.tsx
Labels: patch

#70 Patch/author main page create buttons
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
Labels: patch

#73 Hotfix/user years of experience
  frontend/src/screens/StudentSettings/containers/Settings/index.tsx
  frontend/src/screens/StudentSettings/containers/Settings/options.tsx
Labels: bug

#74 Added whitelisted methods for data fetch when user not logged in
  backend/core/src/main/java/com/knewless/core/security/SecurityConfiguration.java
Labels: bug, patch

#72 Patch/34 Added rating as mocked data for Course cards at Add Path page
  backend/core/src/main/resources/db/migration/V15__make_clarkkent_author.sql
  frontend/src/containers/Routing/index.tsx
  frontend/src/screens/AddPath/components/ClickableCourseCard/index.tsx
  frontend/src/screens/AddPath/components/ClickableCourseCard/styles.module.sass
Labels: patch

#76 Fix/94 registration
  frontend/src/components/RegisterForm/index.tsx
  frontend/src/components/RegisterForm/styles.module.sass
  frontend/src/containers/Notifications/sagas.ts
  frontend/src/helpers/api.helper.ts
Labels: patch

#77 Feature/114 Now real rating is used at Add Path page
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseMapper.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseWithMinutesDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseWithMinutesProjection.java
  backend/core/src/main/resources/application.properties
  frontend/src/screens/AddPath/components/ClickableCourseCard/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/sagas.ts
  frontend/src/screens/AddPath/models/domain.ts
Labels: enhancement

#79 Fixed author main page displaying for resolutions till 1024x576
  frontend/src/screens/AuthorMainPage/components/AuthorInfoBlock/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorInfoBlock/styles.module.sass
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
  frontend/src/screens/AuthorMainPage/containers/MainPage/styles.module.sass
  frontend/src/screens/AuthorMainPage/models/IAuthor.ts
  frontend/src/screens/AuthorMainPage/services/author.page.mock.ts
Labels: bug

#82 Implemented displaying email in user's popup when clicking on avatar
  backend/core/src/main/java/com/knewless/core/user/dto/UserDto.java
  frontend/src/components/Header/PopupMenu/index.tsx
  frontend/src/components/Header/PopupMenu/styles.module.sass
  frontend/src/components/Header/UserElement/index.tsx
  frontend/src/components/Header/UserElement/styles.module.sass
  frontend/src/containers/AppRouter/models/IUser.ts
Labels: enhancement

#84 Added placeholder instead of grey circle
  frontend/src/components/avatar/AvatarUploader/index.tsx
Labels: patch

#85 Added proper (for now) logic to handle save failure and save success
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/sagas.ts
  frontend/src/screens/AddPath/services/add_page.service.ts
Labels: patch

#86 Fix/117 registration
  frontend/src/components/RegisterForm/index.tsx
Labels: patch

#89 Update docker-compose.dev.yml
  .docker/docker-compose.dev.yml
Labels: patch

#90 Fixed search to properly display on pages other than landing
  frontend/src/components/Header/index.tsx
Labels: patch

#92 Hotfix/author real data
  backend/core/src/main/java/com/knewless/core/author/AuthorController.java
  backend/core/src/main/java/com/knewless/core/author/AuthorRepository.java
  backend/core/src/main/java/com/knewless/core/author/AuthorService.java
  backend/core/src/main/java/com/knewless/core/author/dto/AuthorBriefInfoDto.java
  backend/core/src/main/java/com/knewless/core/author/mapper/AuthorInfoMapper.java
  backend/core/src/main/java/com/knewless/core/author/model/Author.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/path/PathRepository.java
  backend/core/src/main/java/com/knewless/core/school/mapper/SchoolInfoMapper.java
  frontend/src/screens/AuthorMainPage/components/AuthorCardsSegment/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorCardsSegment/styles.module.sass
  frontend/src/screens/AuthorMainPage/components/AuthorInfoBlock/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorInfoBlock/styles.module.sass
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
  frontend/src/screens/AuthorMainPage/containers/MainPage/reducer.ts
  frontend/src/screens/AuthorMainPage/containers/MainPage/sagas.ts
  frontend/src/screens/AuthorMainPage/containers/MainPage/styles.module.sass
  frontend/src/screens/AuthorMainPage/models/IAuthor.ts
  frontend/src/screens/AuthorMainPage/models/ISchool.ts
  frontend/src/screens/AuthorMainPage/reducers/index.ts
  frontend/src/screens/AuthorMainPage/routines/index.ts
  frontend/src/screens/AuthorMainPage/services/author.main.page.service.ts
  frontend/src/screens/AuthorMainPage/services/author.page.mock.ts
  frontend/src/screens/AuthorSettings/containers/Settings/sagas.ts
Labels: bug, patch

#91 Made avatar background filled (at top right corner)
  frontend/src/components/avatar/Avatar/styles.module.sass
Labels: enhancement

#95 Fixed logo
  frontend/src/components/Logo/styles.module.sass
Labels: patch

#99 patch/129 Restyled popup menu when clicking on user's avatar at navbar
  frontend/src/components/Header/PopupMenu/index.tsx
  frontend/src/components/Header/PopupMenu/styles.module.sass
  frontend/src/components/Header/UserElement/styles.module.sass
Labels: patch

#100 feature/110 Added placeholder when there are no courses to select
  frontend/src/assets/images/poem.svg
  frontend/src/components/Confirmation/index.tsx
  frontend/src/components/Confirmation/styles.module.sass
  frontend/src/components/DependenciesSelector/index.tsx
  frontend/src/components/DependenciesSelector/styles.module.sass
  frontend/src/components/FilterableList/index.tsx
  frontend/src/components/ListPlaceholder/index.tsx
  frontend/src/components/ListPlaceholder/styles.module.sass
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/styles.module.sass
Labels: enhancement

#102 Bugfix/134 - Wrong email appearence in user's popup.
  frontend/package.json
  frontend/src/components/Header/PopupMenu/index.tsx
  frontend/src/components/Header/PopupMenu/styles.module.sass
  frontend/src/components/Header/UserElement/index.tsx
  frontend/src/components/Header/UserElement/styles.module.sass
Labels: dependencies, patch

#103 patch/125 Changed placeholder image
  frontend/src/assets/images/empty_list.png
  frontend/src/assets/images/poem.svg
  frontend/src/components/ListPlaceholder/index.tsx
  frontend/src/components/ListPlaceholder/styles.module.sass
Labels: patch

#106 Hotfix/author main page display path with no courses
  backend/core/src/main/java/com/knewless/core/author/AuthorService.java
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/path/PathController.java
  backend/core/src/main/java/com/knewless/core/path/PathRepository.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  frontend/src/screens/AuthorMainPage/services/author.main.page.service.ts
Labels: bug

#110 Bugfix /48 author public page (130, 141)
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/sagas.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/styles.sass
Labels: bug

#108 Patch/139 fix small issues
  backend/core/src/main/java/com/knewless/core/path/PathController.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathCreationRequestDto.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathDto.java
  frontend/src/assets/images/cobweb.png
  frontend/src/components/CourseCard/index.tsx
  frontend/src/components/DependenciesSelector/index.tsx
  frontend/src/components/FilterableList/index.tsx
  frontend/src/components/PathCard/index.tsx
  frontend/src/components/avatar/Avatar/styles.module.sass
  frontend/src/components/avatar/AvatarUploader/index.tsx
  frontend/src/components/avatar/AvatarWithBackground/index.tsx
  frontend/src/components/avatar/AvatarWithBackground/styles.module.sass
  frontend/src/components/buttons/GradientButton/styles.module.sass
  frontend/src/components/placeholder/ListPlaceholder/index.tsx
  frontend/src/components/placeholder/ListPlaceholder/styles.module.sass
  frontend/src/components/placeholder/RowPlaceholder/index.tsx
  frontend/src/components/placeholder/RowPlaceholder/styles.module.sass
  frontend/src/containers/Notifications/index.tsx
  frontend/src/screens/AddCourse/components/LectureCard/styles.module.sass
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorInfoBlock/index.tsx
  frontend/src/screens/AuthorSettings/containers/Settings/index.tsx
  frontend/src/screens/AuthorSettings/containers/Settings/styles.module.sass
  frontend/src/screens/Landing/components/BottomNavigation/index.tsx
  frontend/src/screens/Landing/components/NavigationSection/index.tsx
  frontend/src/screens/Landing/containers/LandingPage/index.tsx
  frontend/src/screens/Landing/services/mock.ts
  frontend/src/screens/StudentPage/containers/StudentProfilePage/index.tsx
  frontend/src/screens/StudentSettings/containers/Settings/index.tsx
  frontend/src/screens/StudentSettings/containers/Settings/options.tsx
  frontend/src/screens/StudentSettings/containers/Settings/styles.module.sass
Labels: enhancement, patch

#114 Feature/138 lecture time tracking
  backend/core/src/main/java/com/knewless/core/history/HistoryRepository.java
  backend/core/src/main/java/com/knewless/core/history/WatchHistoryController.java
  backend/core/src/main/java/com/knewless/core/history/WatchHistoryService.java
  backend/core/src/main/java/com/knewless/core/history/dto/WatchHistorySaveRequest.java
  backend/core/src/main/java/com/knewless/core/history/model/History.java
  backend/core/src/main/java/com/knewless/core/student/StudentService.java
  backend/core/src/main/java/com/knewless/core/student/model/Student.java
  backend/core/src/main/resources/db/migration/V18__add_seconds_to_history.sql
  frontend/src/models/AppState.ts
  frontend/src/screens/LecturePage/containers/Lectures/index.tsx
  frontend/src/screens/LecturePage/containers/Lectures/lecturesList.tsx
  frontend/src/screens/LecturePage/containers/Lectures/lecturesMenu.tsx
  frontend/src/screens/LecturePage/containers/Lectures/reducers.tsx
  frontend/src/screens/LecturePage/containers/Lectures/sagas.tsx
  frontend/src/screens/LecturePage/models/CourseData.tsx
  frontend/src/screens/LecturePage/models/IAuthor.tsx
  frontend/src/screens/LecturePage/models/ICourse.tsx
  frontend/src/screens/LecturePage/models/ICourseData.tsx
  frontend/src/screens/LecturePage/models/ILecturePageState.ts
  frontend/src/screens/LecturePage/models/ILectures.tsx
  frontend/src/screens/LecturePage/models/ILecturesList.tsx
  frontend/src/screens/LecturePage/models/ILecturesMenu.tsx
  frontend/src/screens/LecturePage/reducers/index.tsx
  frontend/src/screens/LecturePage/routines/index.tsx
  frontend/src/screens/LecturePage/sagas/index.tsx
  frontend/src/screens/LecturePage/services/player.service.ts
  frontend/src/services/use.interval.hook.ts
Labels: enhancement

#117 Feature/146 custom exception handling
  .env.example/api.env
  backend/core/src/main/java/com/knewless/core/author/AuthorController.java
  backend/core/src/main/java/com/knewless/core/author/AuthorService.java
  backend/core/src/main/java/com/knewless/core/exception/custom/OAuth2AuthenticationProcessingException.java
  backend/core/src/main/java/com/knewless/core/exception/custom/ResourceNotFoundException.java
  backend/core/src/main/java/com/knewless/core/exception/handling/ApiError.java
  backend/core/src/main/java/com/knewless/core/exception/handling/ApiErrorFactory.java
  backend/core/src/main/java/com/knewless/core/exception/handling/BasicApiError.java
  backend/core/src/main/java/com/knewless/core/exception/handling/RestExceptionHandler.java
  backend/core/src/main/java/com/knewless/core/exception/handling/brief/ShortApiError.java
  backend/core/src/main/java/com/knewless/core/exception/handling/brief/ShortApiErrorFactory.java
  backend/core/src/main/java/com/knewless/core/exception/handling/detailed/DetailedApiError.java
  backend/core/src/main/java/com/knewless/core/exception/handling/detailed/DetailedApiErrorFactory.java
  backend/core/src/main/java/com/knewless/core/exception/handling/detailed/suberror/ApiSubError.java
  backend/core/src/main/java/com/knewless/core/exception/handling/detailed/suberror/PlainMessageError.java
  backend/core/src/main/java/com/knewless/core/security/oauth/oauth2/CustomOAuth2UserService.java
  backend/core/src/main/java/com/knewless/core/security/oauth/oauth2/user/OAuth2UserInfoFactory.java
  backend/core/src/main/java/com/knewless/core/student/StudentService.java
  backend/core/src/main/java/com/knewless/core/user/UserService.java
  backend/core/src/main/resources/application.properties
  backend/core/src/test/resources/application.properties
Labels: enhancement

#109 Patch/91 all fields validation
  backend/core/src/main/java/com/knewless/core/auth/AuthController.java
  backend/core/src/main/java/com/knewless/core/auth/AuthService.java
  backend/core/src/main/java/com/knewless/core/author/AuthorController.java
  backend/core/src/main/java/com/knewless/core/author/AuthorService.java
  backend/core/src/main/java/com/knewless/core/author/dto/AuthorSettingsDto.java
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/CreateCourseRequestDto.java
  backend/core/src/main/java/com/knewless/core/exception/UserAlreadyRegisteredException.java
  backend/core/src/main/java/com/knewless/core/lecture/Dto/SaveLectureDto.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureController.java
  backend/core/src/main/java/com/knewless/core/path/PathController.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathCreationRequestDto.java
  backend/core/src/main/java/com/knewless/core/security/model/LoginRequest.java
  backend/core/src/main/java/com/knewless/core/security/model/SignUpRequest.java
  backend/core/src/main/java/com/knewless/core/student/StudentController.java
  backend/core/src/main/java/com/knewless/core/student/StudentService.java
  backend/core/src/main/java/com/knewless/core/student/dto/StudentSettingsDto.java
  backend/core/src/main/java/com/knewless/core/validation/SingleMessageResponse.java
  backend/core/src/main/java/com/knewless/core/validation/ValidationMessageCreator.java
  frontend/src/components/LoginForm/index.tsx
  frontend/src/components/RegisterForm/index.tsx
  frontend/src/helpers/validation.helper.ts
  frontend/src/screens/AddCourse/components/UploadLectureModal/index.tsx
  frontend/src/screens/AddCourse/components/UploadLectureModal/styles.module.sass
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddCourse/containers/AddCoursePage/styles.module.sass
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/styles.module.sass
  frontend/src/screens/Authentication/containers/sagas.tsx
  frontend/src/screens/AuthorSettings/containers/Settings/index.tsx
  frontend/src/screens/AuthorSettings/containers/Settings/styles.module.sass
  frontend/src/screens/StudentSettings/containers/Settings/index.tsx
  frontend/src/screens/StudentSettings/containers/Settings/options.tsx
  frontend/src/screens/StudentSettings/containers/Settings/styles.module.sass
Labels: patch

#121 Hotfix/author main page courses query
  backend/core/src/main/java/com/knewless/core/author/AuthorController.java
  backend/core/src/main/java/com/knewless/core/author/AuthorRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/dto/AuthorCourseQueryResult.java
Labels: bug

#126 Patch/87 twitter input prefix
  backend/core/src/main/java/com/knewless/core/author/dto/AuthorSettingsDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CreateCourseRequestDto.java
  backend/core/src/main/java/com/knewless/core/lecture/Dto/SaveLectureDto.java
  backend/core/src/main/java/com/knewless/core/path/PathController.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathCreationRequestDto.java
  backend/core/src/main/java/com/knewless/core/student/dto/StudentSettingsDto.java
  frontend/src/helpers/validation.helper.ts
  frontend/src/screens/AuthorSettings/containers/Settings/index.tsx
  frontend/src/screens/AuthorSettings/containers/Settings/styles.module.sass
  frontend/src/screens/StudentSettings/containers/Settings/index.tsx
Labels: patch

#123 Patch/85 settings saved message
  backend/core/src/main/java/com/knewless/core/author/AuthorController.java
  backend/core/src/main/java/com/knewless/core/student/StudentController.java
  frontend/src/screens/AuthorSettings/containers/Settings/sagas.ts
  frontend/src/screens/StudentSettings/containers/Settings/sagas.ts
  frontend/src/screens/StudentSettings/services/settings.service.ts
Labels: patch

#122 Revert get mapping deletion for 'author/self-info' endpoint
  backend/core/src/main/java/com/knewless/core/author/AuthorController.java
Labels: bug

#104 Feature/60 elastic db
  .docker/docker-compose.dev.yml
  .docker/docker-compose.yml
  .env.example/api.env
  .env.example/elastic.env
  backend/core/build.gradle
  backend/core/src/main/java/com/knewless/core/author/AuthorRepository.java
  backend/core/src/main/java/com/knewless/core/author/AuthorService.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/EsConfiguration.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/EsController.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/EsRepository.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/EsService.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/model/EsDataType.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/model/EsEntity.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/model/EsMapper.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/model/SearchDto.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureRepository.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  backend/core/src/main/java/com/knewless/core/security/SecurityConfiguration.java
  backend/core/src/main/resources/application.properties
  backend/core/src/main/resources/elasticsearch/es-config.json
  backend/core/src/test/resources/application.properties
  frontend/package.json
  frontend/src/components/Header/index.tsx
  frontend/src/components/Header/styles.module.sass
  frontend/src/components/RegisterForm/styles.module.sass
  frontend/src/models/AppState.ts
  frontend/src/reducers/index.ts
  frontend/src/sagas/index.ts
  frontend/src/screens/Landing/containers/LandingPage/index.tsx
  frontend/src/screens/Search/containers/SearchHeader/index.tsx
  frontend/src/screens/Search/containers/SearchHeader/styles.module.sass
  frontend/src/screens/Search/containers/reducer.ts
  frontend/src/screens/Search/models/ISearchData.ts
  frontend/src/screens/Search/models/ISearchState.ts
  frontend/src/screens/Search/reducer/reducer.ts
  frontend/src/screens/Search/routines/routines.ts
  frontend/src/screens/Search/sagas/sagas.ts
  frontend/src/screens/Search/services/service.ts
Labels: enhancement

#124 Feature/57 add courses page
  backend/core/src/main/java/com/knewless/core/author/AuthorController.java
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseMapper.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseDetailsDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseDetailsQueryResult.java
  backend/core/src/main/java/com/knewless/core/currentUserCource/CurrentUserCourseController.java
  backend/core/src/main/java/com/knewless/core/currentUserCource/CurrentUserCourseService.java
  backend/core/src/main/java/com/knewless/core/tag/TagRepository.java
  backend/core/src/main/java/com/knewless/core/user/UserService.java
  backend/core/src/main/resources/application.yml
  frontend/src/components/CoursePreview/index.tsx
  frontend/src/components/CoursePreview/styles.module.sass
  frontend/src/components/Header/UserElement/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/StyledRating/index.tsx
  frontend/src/containers/Notifications/index.tsx
  frontend/src/containers/Routing/index.tsx
  frontend/src/models/AppState.ts
  frontend/src/reducers/index.ts
  frontend/src/sagas/index.ts
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
  frontend/src/screens/Courses/components/AllCourses/index.tsx
  frontend/src/screens/Courses/components/MyCourses/index.tsx
  frontend/src/screens/Courses/containers/CoursesPage/index.tsx
  frontend/src/screens/Courses/containers/CoursesPage/reducer.ts
  frontend/src/screens/Courses/containers/CoursesPage/sagas.ts
  frontend/src/screens/Courses/containers/CoursesPage/styles.module.sass
  frontend/src/screens/Courses/models/ICourseItem.ts
  frontend/src/screens/Courses/models/ICoursesData.ts
  frontend/src/screens/Courses/models/ICoursesState.ts
  frontend/src/screens/Courses/models/ITag.ts
  frontend/src/screens/Courses/reducers/index.ts
  frontend/src/screens/Courses/routines/index.ts
  frontend/src/screens/Courses/sagas/index.ts
  frontend/src/screens/Courses/services/courses.page.service.ts
  frontend/src/screens/MainPage/containers/MainStudentPage/index.tsx
  frontend/tsconfig.json
Labels: enhancement

#129 fix: check list size
  backend/core/src/main/java/com/knewless/core/elasticsearch/EsService.java
Labels: patch

#132 Fix double-click
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/sagas.tsx
  frontend/src/screens/AuthorPublicPage/services/publicAuthorPageService.tsx
Labels: bug

#130 Bugfix/135 refreshing page
  frontend/src/components/CoursePreview/styles.module.sass
  frontend/src/components/LoaderWrapper/index.tsx
  frontend/src/containers/AppRouter/models/IAppRouterState.ts
  frontend/src/containers/AppRouter/reducer.ts
  frontend/src/containers/RootRoute/index.tsx
Labels: bug

#131 fix: check role existence
  backend/core/src/main/java/com/knewless/core/user/UserRepository.java
  backend/core/src/main/java/com/knewless/core/user/UserService.java
Labels: bug

#133 Fixed high image display
  frontend/src/components/PathCard/styles.module.sass
Labels: patch

#134 Removed console.log
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
Labels: patch

#136 Fix/162 role
  frontend/src/containers/AppRouter/index.tsx
Labels: bug

#135 Bugfix/163 trim description
  backend/core/src/main/java/com/knewless/core/user/UserService.java
  frontend/src/components/CoursePreview/index.tsx
  frontend/src/components/CoursePreview/styles.module.sass
Labels: bug

#139 Removed duplicate method
  backend/core/src/main/java/com/knewless/core/user/UserService.java
  frontend/src/components/CoursePreview/index.tsx
Labels: patch

#140 Hotfix/create course preview author name
  frontend/src/components/CoursePreview/index.tsx
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/StudentSettings/containers/Settings/index.tsx
  frontend/src/screens/StudentSettings/containers/Settings/sagas.ts
Labels: bug

#138 Fix/173 dropdown
  backend/core/src/main/resources/elasticsearch/es-config.json
  frontend/src/screens/Search/containers/SearchHeader/index.tsx
Labels: bug, enhancement

#144 Hotfix/166 author self subscription
  backend/core/src/main/java/com/knewless/core/author/AuthorService.java
  backend/core/src/main/java/com/knewless/core/author/dto/AuthorPublicDto.java
  backend/core/src/main/java/com/knewless/core/subscription/SubscriptionController.java
  backend/core/src/main/java/com/knewless/core/subscription/SubscriptionService.java
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/index.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/reducers.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/styles.sass
  frontend/src/screens/AuthorPublicPage/models/IAuthorData.tsx
Labels: bug

#158 Hotfix/171 course page shifted lecture names
  frontend/src/screens/AddCourse/components/LectureCard/styles.module.sass
  frontend/src/screens/CoursePage/components/CourseMenu/index.tsx
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
Labels: bug

#159 patch/199-course-page-discussion-icon-redesign
  frontend/src/screens/CoursePage/components/CourseMenu/index.tsx
  frontend/src/screens/CoursePage/components/CourseMenu/styles.module.sass
  frontend/src/screens/CoursePage/icons/discussion.svg
Labels: patch

#160 Hotfix/193 lecture page author link
  frontend/src/screens/LecturePage/containers/Lectures/index.tsx
  frontend/src/screens/LecturePage/containers/Lectures/styles.sass
Labels: bug

#161 Hotfix/203 unspecified author while loading
  frontend/src/reducers/index.ts
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/index.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/reducers.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/styles.module.sass
Labels: bug

#162 hotfix/180-courses-sorting-order
  frontend/src/screens/PathPage/components/CoursesList/index.tsx
Labels: bug

#163 Feature/58 paths page
  backend/core/src/main/java/com/knewless/core/path/PathController.java
  backend/core/src/main/java/com/knewless/core/path/PathRepository.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  backend/core/src/main/java/com/knewless/core/security/SecurityConfiguration.java
  frontend/src/containers/Routing/index.tsx
  frontend/src/models/AppState.ts
  frontend/src/reducers/index.ts
  frontend/src/sagas/index.ts
  frontend/src/screens/Paths/components/AllPaths/index.tsx
  frontend/src/screens/Paths/components/MyPaths/index.tsx
  frontend/src/screens/Paths/containers/PathsPage/index.tsx
  frontend/src/screens/Paths/containers/PathsPage/reducer.ts
  frontend/src/screens/Paths/containers/PathsPage/sagas.ts
  frontend/src/screens/Paths/containers/PathsPage/styles.module.sass
  frontend/src/screens/Paths/models/IPathsData.ts
  frontend/src/screens/Paths/models/IPathsState.ts
  frontend/src/screens/Paths/reducers/index.ts
  frontend/src/screens/Paths/routines/index.ts
  frontend/src/screens/Paths/sagas/index.ts
  frontend/src/screens/Paths/services/paths.service.ts
Labels: enhancement

#164 Hotfix/195 not clickable author name
  frontend/src/models/AppState.ts
  frontend/src/screens/PathPage/components/PathMenu/index.tsx
  frontend/src/screens/PathPage/components/PathOverview/index.tsx
  frontend/src/screens/PathPage/containers/PathPage/index.tsx
Labels: bug

#165 hotfix/210-open-lecture-in-new-tab
  frontend/src/screens/CoursePage/components/CourseMenu/index.tsx
Labels: bug

#166 hotfix/202-header-menu-author-profile-link
  frontend/src/components/Header/PopupMenu/index.tsx
  frontend/src/components/Header/UserElement/index.tsx
  frontend/src/components/Header/index.tsx
Labels: bug

#167 Patch/133 settings location search
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/index.tsx
  frontend/src/screens/AuthorSettings/containers/Settings/index.tsx
  frontend/src/screens/AuthorSettings/containers/Settings/options.tsx
  frontend/src/screens/StudentSettings/containers/Settings/index.tsx
Labels: patch

#168 Hotfix/214 company validation and lvl sorting
  backend/core/src/main/java/com/knewless/core/author/dto/AuthorSettingsDto.java
  backend/core/src/main/java/com/knewless/core/student/dto/StudentSettingsDto.java
  frontend/src/helpers/validation.helper.ts
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
  frontend/src/screens/PathPage/components/CoursesList/index.tsx
Labels: bug

#172 Used common PathCard component
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
Labels: patch

#171 Added ability to edit course
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/CreateCourseRequestDto.java
  backend/core/src/main/java/com/knewless/core/course/model/Course.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/EsRepository.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/EsService.java
  backend/core/src/main/java/com/knewless/core/lecture/model/Lecture.java
  frontend/src/containers/Routing/index.tsx
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddCourse/containers/AddCoursePage/reducer.ts
  frontend/src/screens/AddCourse/containers/AddCoursePage/sagas.ts
  frontend/src/screens/AddCourse/models/ICourse.ts
  frontend/src/screens/AddCourse/models/ICourseData.ts
  frontend/src/screens/AddCourse/models/IUpdateCourse.ts
  frontend/src/screens/AddCourse/routines/index.ts
  frontend/src/screens/AddCourse/services/course.service.ts
  frontend/src/screens/CoursePage/components/CourseOverview/index.tsx
  frontend/src/screens/CoursePage/components/CourseOverview/styles.module.sass
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
  frontend/src/screens/MainPage/containers/MainStudentPage/index.tsx
Labels: enhancement

#174 Features/197 path editing page
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/EsService.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/model/EsMapper.java
  backend/core/src/main/java/com/knewless/core/path/PathController.java
  backend/core/src/main/java/com/knewless/core/path/PathMapper.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathDetailsDto.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathUpdateRequestDto.java
  backend/core/src/main/java/com/knewless/core/security/SecurityConfiguration.java
  frontend/src/sagas/index.ts
  frontend/src/screens/AddCourse/containers/AddCoursePage/sagas.ts
  frontend/src/screens/AddCourse/services/course.service.ts
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/reducer.ts
  frontend/src/screens/AddPath/containers/AddPathPage/sagas.ts
  frontend/src/screens/AddPath/models/AddPathData.ts
  frontend/src/screens/AddPath/models/domain.ts
  frontend/src/screens/AddPath/routines/index.ts
  frontend/src/screens/AddPath/services/add_page.service.ts
Labels: enhancement

#179 Fixed cursor not changing to a pointer for the whole "log out" button's height
  frontend/src/components/Header/PopupMenu/styles.module.sass
Labels: patch

#177 Feature/97 rating
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseMapper.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/courseReaction/CourseReactionRepository.java
  backend/core/src/main/java/com/knewless/core/course/courseReaction/model/CourseReaction.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseFullInfoDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseToPlayerDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/RatingCourseRequestDto.java
  backend/core/src/main/java/com/knewless/core/db/BaseRating.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/EsService.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/model/EsMapper.java
  backend/core/src/main/java/com/knewless/core/security/SecurityConfiguration.java
  backend/core/src/main/java/com/knewless/core/user/UserService.java
  backend/core/src/main/resources/application.yml
  backend/core/src/main/resources/db/migration/V22__edit_course_reaction.sql
  frontend/src/components/RatingModal/index.tsx
  frontend/src/components/RatingModal/styles.module.sass
  frontend/src/components/StyledRating/index.tsx
  frontend/src/screens/CoursePage/components/CourseInfo/index.tsx
  frontend/src/screens/CoursePage/components/CourseInfo/styles.module.sass
  frontend/src/screens/CoursePage/components/CourseMenu/index.tsx
  frontend/src/screens/CoursePage/components/CourseOverview/index.tsx
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
  frontend/src/screens/CoursePage/containers/CoursePage/reducer.ts
  frontend/src/screens/CoursePage/containers/CoursePage/sagas.ts
  frontend/src/screens/CoursePage/models/ICoursePageState.ts
  frontend/src/screens/CoursePage/models/IFullCourseData.ts
  frontend/src/screens/CoursePage/reducers/index.ts
  frontend/src/screens/CoursePage/routines/index.ts
  frontend/src/screens/CoursePage/services/course.service.ts
  frontend/src/screens/LecturePage/containers/Lectures/index.tsx
  frontend/src/screens/LecturePage/containers/Lectures/reducers.tsx
  frontend/src/screens/LecturePage/models/ICourseData.tsx
  frontend/src/screens/LecturePage/routines/index.tsx
Labels: enhancement

#180 Added time format in cards
  backend/core/src/main/java/com/knewless/core/course/CourseMapper.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/AuthorCourseDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseFullInfoDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseProfileDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseWithMinutesDto.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureMapper.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureService.java
  backend/core/src/main/java/com/knewless/core/lecture/dto/LectureCreateResponseDto.java
  backend/core/src/main/java/com/knewless/core/lecture/dto/ShortLectureDto.java
  backend/core/src/main/java/com/knewless/core/path/PathMapper.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  backend/core/src/main/java/com/knewless/core/path/dto/AuthorPathDto.java
  backend/core/src/main/java/com/knewless/core/path/dto/AuthorPathQueryResult.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathDetailsDto.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathDto.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathDurationDto.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathQueryResult.java
  frontend/src/components/CourseCard/index.tsx
  frontend/src/components/CoursePreview/index.tsx
  frontend/src/components/PathCard/helper.ts
  frontend/src/components/PathCard/index.tsx
  frontend/src/helpers/time.helper.ts
  frontend/src/screens/AddCourse/components/LectureCard/index.tsx
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddCourse/models/ILecture.ts
  frontend/src/screens/AddCourse/services/helper.service.ts
  frontend/src/screens/AddPath/components/ClickableCourseCard/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/models/domain.ts
  frontend/src/screens/AuthorMainPage/components/AuthorPathCard/index.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/authorCoursesList.tsx
  frontend/src/screens/CoursePage/components/CourseInfo/index.tsx
  frontend/src/screens/CoursePage/components/CourseMenu/index.tsx
  frontend/src/screens/CoursePage/components/CourseOverview/index.tsx
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
  frontend/src/screens/CoursePage/models/IFullCourseData.ts
  frontend/src/screens/CoursePage/models/ILectureData.ts
  frontend/src/screens/LecturePage/containers/Lectures/lecturesList.tsx
  frontend/src/screens/PathPage/components/PathOverview/index.tsx
  frontend/src/screens/PathPage/containers/PathPage/index.tsx
  frontend/src/screens/StudentPage/components/CompletedCourse/index.tsx
  frontend/src/screens/StudentPage/components/CurrentCourse/index.tsx
  frontend/src/screens/StudentPage/containers/StudentProfilePage/index.tsx
  frontend/src/screens/StudentPage/models/ICourse.ts
Labels: patch

#183 fix: small fixes
  frontend/src/components/RatingModal/index.tsx
  frontend/src/containers/AppRouter/index.tsx
  frontend/src/containers/AppRouter/sagas.ts
Labels: patch

#184 Fix/237 shifting
  frontend/src/components/RegisterForm/styles.module.sass
  frontend/src/screens/CoursePage/components/CourseInfo/index.tsx
Labels: patch

#188 Update index.tsx
  frontend/src/screens/SearchResultsPage/containers/SearchResultsPage/index.tsx
Labels: patch

#187 Fix/237 style
  backend/core/src/main/java/com/knewless/core/course/CourseMapper.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseDetailsDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseDto.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/EsService.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/model/EsMapper.java
  frontend/src/components/CourseCard/index.tsx
  frontend/src/components/CourseCard/styles.module.sass
  frontend/src/components/CoursePreview/index.tsx
  frontend/src/components/CoursePreview/styles.module.sass
  frontend/src/containers/AppRouter/sagas.ts
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddPath/components/ClickableCourseCard/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/models/domain.ts
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/authorCoursesList.tsx
  frontend/src/screens/CoursePage/components/CourseInfo/index.tsx
  frontend/src/screens/Courses/components/AllCourses/index.tsx
  frontend/src/screens/Courses/components/MyCourses/index.tsx
  frontend/src/screens/Courses/models/ICourseItem.ts
  frontend/src/screens/Landing/containers/LandingPage/index.tsx
  frontend/src/screens/MainPage/containers/MainStudentPage/index.tsx
  frontend/src/screens/SearchResultsPage/components/course/Segment/index.tsx
  frontend/src/screens/SearchResultsPage/models/EsModels.ts
Labels: patch

#185 Feature/179 time format
  backend/core/src/main/java/com/knewless/core/author/dto/AuthorShortDto.java
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/path/PathController.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathDetailsDto.java
  frontend/src/helpers/time.helper.ts
  frontend/src/screens/AddCourse/components/LectureCard/index.tsx
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddCourse/containers/AddCoursePage/sagas.ts
  frontend/src/screens/AddCourse/models/ICourseState.ts
  frontend/src/screens/AddCourse/reducers/index.ts
  frontend/src/screens/AddCourse/services/course.service.ts
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/sagas.ts
  frontend/src/screens/AddPath/models/AddPathState.ts
  frontend/src/screens/AddPath/models/domain.ts
  frontend/src/screens/AddPath/reducers/index.ts
  frontend/src/screens/CoursePage/components/CourseOverview/index.tsx
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
  frontend/src/screens/CoursePage/containers/CoursePage/reducer.ts
  frontend/src/screens/CoursePage/containers/CoursePage/sagas.ts
  frontend/src/screens/CoursePage/models/ICoursePageData.ts
  frontend/src/screens/CoursePage/routines/index.ts
  frontend/src/screens/CoursePage/services/course.service.ts
  frontend/src/screens/StudentPage/components/CompletedCourse/index.tsx
  frontend/src/screens/StudentPage/components/CurrentCourse/index.tsx
Labels: patch

#190 Added footer everywhere and the same bottom margin
  frontend/src/containers/Routing/index.tsx
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AuthorMainPage/containers/MainPage/styles.module.sass
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/styles.module.sass
  frontend/src/screens/AuthorSettings/containers/Settings/styles.module.sass
  frontend/src/screens/CoursePage/components/AuthorInfo/styles.module.sass
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
  frontend/src/screens/CoursePage/containers/CoursePage/styles.module.sass
  frontend/src/screens/Courses/containers/CoursesPage/styles.module.sass
  frontend/src/screens/Landing/containers/LandingPage/index.tsx
  frontend/src/screens/MainPage/containers/MainStudentPage/styles.module.sass
  frontend/src/screens/PathPage/containers/PathPage/index.tsx
  frontend/src/screens/Paths/containers/PathsPage/index.tsx
  frontend/src/screens/Paths/containers/PathsPage/styles.module.sass
  frontend/src/screens/SearchResultsPage/containers/SearchResultsPage/index.tsx
  frontend/src/screens/SearchResultsPage/containers/SearchResultsPage/styles.module.sass
  frontend/src/screens/StudentSettings/containers/Settings/styles.module.sass
  frontend/src/styles/common_variables.sass
Labels: patch

#193 Feature/194 markdown
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseFullInfoDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CreateCourseRequestDto.java
  backend/core/src/main/java/com/knewless/core/course/model/Course.java
  backend/core/src/main/resources/db/migration/V24__add_overview_to_course.sql
  frontend/package.json
  frontend/src/components/OverviewModal/index.tsx
  frontend/src/components/OverviewModal/styles.module.sass
  frontend/src/helpers/validation.helper.ts
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddCourse/containers/AddCoursePage/styles.module.sass
  frontend/src/screens/AddCourse/models/ICourse.ts
  frontend/src/screens/CoursePage/components/CourseOverview/index.tsx
  frontend/src/screens/CoursePage/components/CourseOverview/styles.module.sass
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
  frontend/src/screens/CoursePage/models/IFullCourseData.ts
Labels: enhancement

#203 Fix/251 256 small fixes
  frontend/src/components/LogoWithText/styles.module.sass
  frontend/src/screens/SearchResultsPage/components/path/Segment/index.tsx
Labels: bug

#202 Hotfix/227 undefined lecture data
  frontend/src/screens/LecturePage/containers/Lectures/index.tsx
  frontend/src/screens/LecturePage/containers/Lectures/reducers.tsx
Labels: bug

#201 feat: add user cleanup
  .env.example/api.env
  backend/core/src/main/java/com/knewless/core/security/SecurityConfiguration.java
  backend/core/src/main/java/com/knewless/core/user/UserRepository.java
  backend/core/src/main/java/com/knewless/core/user/UserService.java
  backend/core/src/main/resources/application.properties
Labels: enhancement

#200 feat: add resume button logic
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseFullInfoDto.java
  backend/core/src/main/java/com/knewless/core/history/WatchHistoryService.java
  frontend/src/screens/CoursePage/components/CourseOverview/index.tsx
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
  frontend/src/screens/CoursePage/models/IFullCourseData.ts
Labels: enhancement

#199 Hotfix/249 author main page path link
  backend/core/src/main/java/com/knewless/core/path/PathRepository.java
  backend/core/src/main/java/com/knewless/core/path/dto/AuthorPathDto.java
  backend/core/src/main/java/com/knewless/core/path/dto/AuthorPathQueryResult.java
  frontend/src/screens/AuthorMainPage/components/AuthorPathCard/index.tsx
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
Labels: bug

#205 Hotfix/249 author main page path link
  frontend/src/screens/AuthorMainPage/components/AuthorPathCard/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorPathCard/styles.module.sass
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
  frontend/src/screens/AuthorMainPage/models/IAuthorMainPageData.ts
Labels: bug

#204 fix: after finishing course video stops
  frontend/src/containers/Routing/index.tsx
  frontend/src/containers/Routing/styles.module.sass
  frontend/src/screens/AuthorMainPage/containers/MainPage/styles.module.sass
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/styles.module.sass
  frontend/src/screens/Courses/containers/CoursesPage/styles.module.sass
  frontend/src/screens/LecturePage/containers/Lectures/index.tsx
  frontend/src/screens/MainPage/containers/MainStudentPage/index.tsx
  frontend/src/screens/Paths/containers/PathsPage/styles.module.sass
Labels: bug

#197 Feature/159 history page
  backend/core/src/main/java/com/knewless/core/history/HistoryMapper.java
  backend/core/src/main/java/com/knewless/core/history/HistoryRepository.java
  backend/core/src/main/java/com/knewless/core/history/WatchHistoryController.java
  backend/core/src/main/java/com/knewless/core/history/WatchHistoryService.java
  backend/core/src/main/java/com/knewless/core/history/dto/HistoryDto.java
  backend/core/src/main/java/com/knewless/core/lecture/dto/LectureHistoryDto.java
  backend/core/src/main/java/com/knewless/core/lecture/model/Lecture.java
  backend/core/src/main/resources/db/migration/V25__add_lecture_preview.sql
  backend/fileprocessor/src/main/java/fileprocessor/lecture/model/Lecture.java
  backend/fileprocessor/src/main/java/fileprocessor/videoencoder/VideoEncoderService.java
  frontend/src/assets/images/lecture_image_paceholder.png
  frontend/src/components/Header/PopupMenu/index.tsx
  frontend/src/containers/Routing/index.tsx
  frontend/src/helpers/time.helper.ts
  frontend/src/models/AppState.ts
  frontend/src/reducers/index.ts
  frontend/src/sagas/index.ts
  frontend/src/screens/History/components/HistoryItem/index.tsx
  frontend/src/screens/History/containers/HistoryPage/index.tsx
  frontend/src/screens/History/containers/HistoryPage/reducer.ts
  frontend/src/screens/History/containers/HistoryPage/sagas.ts
  frontend/src/screens/History/containers/HistoryPage/styles.module.sass
  frontend/src/screens/History/models/IHistory.ts
  frontend/src/screens/History/models/IHistoryData.ts
  frontend/src/screens/History/models/IHistoryLecture.ts
  frontend/src/screens/History/models/IHistoryState.ts
  frontend/src/screens/History/reducers/index.tsx
  frontend/src/screens/History/routines/index.ts
  frontend/src/screens/History/sagas/index.tsx
  frontend/src/screens/History/services/history.page.service.ts
Labels: enhancement

#191 Feature/208 author courses circle packing chart
  backend/core/src/main/java/com/knewless/core/author/AuthorService.java
  backend/core/src/main/java/com/knewless/core/course/model/Course.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureController.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureService.java
  backend/core/src/main/java/com/knewless/core/lecture/dto/SaveLectureDto.java
  backend/core/src/main/java/com/knewless/core/lecture/model/Lecture.java
  backend/core/src/main/java/com/knewless/core/notification/model/Notification.java
  backend/core/src/main/java/com/knewless/core/tag/model/Tag.java
  backend/core/src/main/java/com/knewless/core/user/model/User.java
  frontend/package.json
  frontend/src/components/Charts/ChartWrapper.tsx
  frontend/src/components/Charts/CirclePackingChart.js
  frontend/src/components/Charts/DonutChart.js
  frontend/src/components/CoursePreview/index.tsx
  frontend/src/helpers/validation.helper.ts
  frontend/src/screens/AddCourse/components/UploadLectureModal/index.tsx
  frontend/src/screens/AddCourse/components/UploadLectureModal/styles.module.sass
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddCourse/containers/AddCoursePage/reducer.ts
  frontend/src/screens/AddCourse/containers/AddCoursePage/sagas.ts
  frontend/src/screens/AddCourse/models/ICourseData.ts
  frontend/src/screens/AddCourse/models/ICourseState.ts
  frontend/src/screens/AddCourse/models/IUpdateCourse.ts
  frontend/src/screens/AddCourse/models/lectures.json
  frontend/src/screens/AddCourse/reducers/index.ts
  frontend/src/screens/AddCourse/routines/index.ts
  frontend/src/screens/AddCourse/services/add-course.service.ts
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/sagas.ts
  frontend/src/screens/AddPath/services/add-path.service.ts
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/index.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/sagas.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/styles.module.sass
  frontend/src/screens/AuthorPublicPage/services/publicAuthorPageService.tsx
Labels: enhancement

#206 Update application.properties
  backend/core/src/test/resources/application.properties
Labels: patch

#207 Hotfix/268 add missing links to cards
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseQueryResult.java
  backend/core/src/main/java/com/knewless/core/currentUserCource/CurrentUserCourseController.java
  backend/core/src/main/java/com/knewless/core/currentUserCource/CurrentUserCourseService.java
  frontend/src/components/CourseCard/index.tsx
  frontend/src/components/CourseCard/styles.module.sass
  frontend/src/screens/AuthorMainPage/components/AuthorCourseCard/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorCourseCard/styles.module.sass
  frontend/src/screens/CoursePage/components/AuthorInfo/index.tsx
  frontend/src/screens/CoursePage/components/CoursesList/index.tsx
  frontend/src/screens/CoursePage/components/CoursesList/styles.module.sass
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
  frontend/src/screens/MainPage/containers/MainStudentPage/index.tsx
  frontend/src/screens/PathPage/components/PathMenu/index.tsx
  frontend/src/screens/PathPage/containers/PathPage/index.tsx
  frontend/src/screens/PathPage/models/ICourse.ts
  frontend/src/screens/PathPage/models/IPath.ts
Labels: bug

#208 Patch/161 footer
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
Labels: patch

#210 Hotfix/278 shifted about author section
  frontend/src/screens/PathPage/components/AboutSection/index.tsx
  frontend/src/screens/PathPage/components/AboutSection/styles.module.sass
  frontend/src/screens/PathPage/components/AuthorCard/index.tsx
Labels: bug, patch

#209 Hotfix/207 show spinner on profile loading
  frontend/src/screens/StudentPage/containers/StudentProfilePage/index.tsx
  frontend/src/screens/StudentPage/containers/StudentProfilePage/sagas.ts
  frontend/src/screens/StudentPage/models/IStudentProfile.ts
Labels: bug

#213 Feature/101 personal goal for student
  backend/core/src/main/java/com/knewless/core/dailyProgress/DailyProgressController.java
  backend/core/src/main/java/com/knewless/core/dailyProgress/DailyProgressRepository.java
  backend/core/src/main/java/com/knewless/core/dailyProgress/DailyProgressService.java
  backend/core/src/main/java/com/knewless/core/dailyProgress/model/DailyProgress.java
  backend/core/src/main/java/com/knewless/core/history/WatchHistoryService.java
  backend/core/src/main/java/com/knewless/core/history/model/History.java
  backend/core/src/main/java/com/knewless/core/progressGoal/ProgressGoalController.java
  backend/core/src/main/java/com/knewless/core/progressGoal/ProgressGoalRepository.java
  backend/core/src/main/java/com/knewless/core/progressGoal/ProgressGoalService.java
  backend/core/src/main/java/com/knewless/core/progressGoal/dto/ProgressGoalBriefDto.java
  backend/core/src/main/java/com/knewless/core/progressGoal/model/ProgressGoal.java
  backend/core/src/main/java/com/knewless/core/student/StudentController.java
  backend/core/src/main/java/com/knewless/core/student/StudentService.java
  backend/core/src/main/java/com/knewless/core/student/dto/ProgressResponseDto.java
  backend/core/src/main/java/com/knewless/core/student/dto/SetGoalRequest.java
  backend/core/src/main/java/com/knewless/core/student/model/Student.java
  backend/core/src/main/resources/db/migration/V26__add_daily_progress.sql
  frontend/src/components/avatar/Avatar/index.tsx
  frontend/src/components/avatar/Avatar/styles.module.sass
  frontend/src/components/buttons/GradientButton/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/MainPage/components/UserInfoBlock/config/goalMenuConfig.json
  frontend/src/screens/MainPage/components/UserInfoBlock/index.tsx
  frontend/src/screens/MainPage/components/UserInfoBlock/styles.module.sass
  frontend/src/screens/MainPage/containers/MainStudentPage/index.tsx
  frontend/src/screens/MainPage/containers/MainStudentPage/reducer.ts
  frontend/src/screens/MainPage/containers/MainStudentPage/sagas.ts
  frontend/src/screens/MainPage/containers/UserInfoBlock/index.tsx
  frontend/src/screens/MainPage/containers/UserInfoBlock/seconds.helper.ts
  frontend/src/screens/MainPage/containers/UserInfoBlock/styles.module.sass
  frontend/src/screens/MainPage/models/IMainStudentPageData.ts
  frontend/src/screens/MainPage/models/IMainStudentPageState.ts
  frontend/src/screens/MainPage/models/PersonalGoal.ts
  frontend/src/screens/MainPage/reducers/index.ts
  frontend/src/screens/MainPage/routines/index.ts
  frontend/src/screens/MainPage/services/main.page.service.ts
Labels: enhancement

#214 Removed navigation block from path page
  frontend/src/screens/PathPage/containers/PathPage/index.tsx
Labels: patch

#218 Hotfix/225 hide my courses on arrow click
  frontend/src/screens/Courses/components/MyCourses/index.tsx
  frontend/src/screens/Courses/containers/CoursesPage/index.tsx
Labels: bug, patch

#219 Hotfix/293 favourite articles placeholder
  frontend/src/screens/Favourites/components/authors/index.tsx
  frontend/src/screens/Favourites/components/courses/index.tsx
  frontend/src/screens/Favourites/components/lectures/index.tsx
  frontend/src/screens/Favourites/components/paths/index.tsx
  frontend/src/screens/Favourites/containers/FavouritesPage/index.tsx
Labels: bug

#212 Hotfix/277 287 text grammar
  frontend/src/components/RatingModal/index.tsx
  frontend/src/screens/Landing/components/BottomNavigation/index.tsx
  frontend/src/screens/Landing/services/mock.ts
  frontend/src/screens/Paths/components/AllPaths/index.tsx
Labels: bug

#216 Hotfix/288 enable save if settings changed
  frontend/src/screens/AuthorSettings/containers/Settings/index.tsx
  frontend/src/screens/StudentSettings/containers/Settings/index.tsx
Labels: bug

#221 Patch/211 Course card redesign
  frontend/src/components/CourseCard/index.tsx
  frontend/src/components/CoursePreview/index.tsx
  frontend/src/components/CoursePreview/styles.module.sass
Labels: patch

#222 Patch-101/Changed calculation of percents to exact percents
  frontend/src/screens/MainPage/containers/UserInfoBlock/index.tsx
Labels: patch

#217 hotfix/266-duplicate-started-courses-displaying
  frontend/src/screens/Courses/containers/CoursesPage/index.tsx
Labels: bug

#223 patch/278-about-path-description-placeholder
  frontend/src/screens/PathPage/components/AboutSection/index.tsx
  frontend/src/screens/PathPage/components/AboutSection/styles.module.sass
Labels: patch

#228 hotfix/278-path-about-shifted-content
  frontend/src/screens/PathPage/components/AboutSection/styles.module.sass
Labels: bug

#224 Changed java icon
  backend/core/src/main/resources/db/migration/V27__change_java_image.sql
Labels: patch

#225 Hotfix/289 path page tabs loading
  frontend/src/screens/Courses/components/MyCourses/index.tsx
  frontend/src/screens/Courses/containers/CoursesPage/index.tsx
  frontend/src/screens/Courses/containers/CoursesPage/reducer.ts
  frontend/src/screens/Courses/containers/CoursesPage/sagas.ts
  frontend/src/screens/Courses/models/ICoursesState.ts
  frontend/src/screens/Courses/reducers/index.ts
  frontend/src/screens/PathPage/containers/PathPage/index.tsx
  frontend/src/screens/PathPage/containers/PathPage/styles.module.sass
  frontend/src/screens/Paths/containers/PathsPage/index.tsx
  frontend/src/screens/Paths/containers/PathsPage/reducer.ts
Labels: bug

#229 Fix/261 270 edit course bug rating bug
  backend/core/src/main/java/com/knewless/core/course/CourseMapper.java
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddCourse/models/ICourseState.ts
  frontend/src/screens/AddCourse/reducers/index.ts
  frontend/src/screens/CoursePage/components/CourseOverview/index.tsx
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
Labels: bug

#226 Fix/295 291 fixes
  frontend/src/components/PathCard/styles.module.sass
  frontend/src/containers/AppRouter/sagas.ts
  frontend/src/screens/AddPath/components/PathPreview/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/styles.module.sass
  frontend/src/screens/CoursePage/components/CourseOverview/index.tsx
Labels: patch

#232 Fix/290 button
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddCourse/containers/AddCoursePage/styles.module.sass
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/styles.module.sass
  frontend/src/screens/CoursePage/components/CourseOverview/index.tsx
  frontend/src/screens/PathPage/containers/PathPage/styles.module.sass
Labels: bug, enhancement

#230 Hotfix/293 articles placeholder
  frontend/src/screens/Favourites/components/articles/index.tsx
  frontend/src/screens/Favourites/components/articles/styles.module.sass
  frontend/src/screens/Favourites/containers/FavouritesPage/index.tsx
Labels: bug, patch

#231 Patch/101 Changed the way time is formatted
  frontend/src/screens/MainPage/containers/UserInfoBlock/seconds.helper.ts
Labels: patch

#233 Fix/260 271 favourite by author interact edit course
  frontend/src/screens/AddCourse/components/LectureCard/index.tsx
  frontend/src/screens/AddCourse/components/LectureCard/styles.module.sass
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/CoursePage/components/CourseInfo/index.tsx
  frontend/src/screens/CoursePage/components/CourseMenu/index.tsx
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
  frontend/src/screens/LecturePage/containers/Lectures/index.tsx
  frontend/src/screens/LecturePage/containers/Lectures/lecturesList.tsx
  frontend/src/screens/LecturePage/containers/Lectures/lecturesMenu.tsx
Labels: bug
