Repository BinaryStudioAcademy/bsa-2020-knewless, pull requests merged in 2020-09, with the labels that each got.

#234 Fix/299 collapsed tab
  backend/core/src/main/java/com/knewless/core/security/SecurityConfiguration.java
  frontend/src/components/PathCard/styles.module.sass
  frontend/src/screens/Authentication/constants.tsx
  frontend/src/screens/Authentication/containers/LoginPage/index.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/reducers.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/sagas.tsx
  frontend/src/screens/Courses/components/MyCourses/index.tsx
Labels: bug, patch

#236 Fix/297 change favourite tabs order
  backend/core/src/main/java/com/knewless/core/course/CourseMapper.java
  frontend/src/screens/AddCourse/components/UploadLectureModal/index.tsx
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/Favourites/containers/FavouritesPage/index.tsx
Labels: bug

#239 Removed 35 symbols email constraint
  frontend/src/helpers/validation.helper.ts
Labels: patch

#238 Feature/212 Redesign tags tabs
  backend/core/src/main/java/com/knewless/core/history/WatchHistoryService.java
  backend/core/src/main/java/com/knewless/core/student/StudentService.java
  backend/core/src/main/java/com/knewless/core/tag/TagController.java
  backend/core/src/main/java/com/knewless/core/tag/TagRepository.java
  backend/core/src/main/java/com/knewless/core/tag/TagService.java
  frontend/src/components/ConfirmationModal/index.tsx
  frontend/src/components/ConfirmationModal/styles.module.sass
  frontend/src/components/DarkModal/index.tsx
  frontend/src/components/DarkModal/styles.module.sass
  frontend/src/components/Header/PopupMenu/index.tsx
  frontend/src/components/InlineLoaderWrapper/index.tsx
  frontend/src/components/placeholder/RowPlaceholder/index.tsx
  frontend/src/containers/AppRouter/models/IRole.ts
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/CoursePage/components/CourseOverview/index.tsx
  frontend/src/screens/Courses/components/AllCourses/index.tsx
  frontend/src/screens/Courses/components/TagTabSelector/index.tsx
  frontend/src/screens/Courses/components/TagTabSelector/modal.module.sass
  frontend/src/screens/Courses/components/TagTabSelector/tabs.module.sass
  frontend/src/screens/Courses/containers/CoursesPage/index.tsx
  frontend/src/screens/Courses/containers/CoursesPage/reducer.ts
  frontend/src/screens/Courses/containers/CoursesPage/sagas.ts
  frontend/src/screens/Courses/containers/CoursesPage/styles.module.sass
  frontend/src/screens/Courses/models/ICoursesState.ts
  frontend/src/screens/Courses/reducers/index.ts
  frontend/src/screens/Courses/routines/index.ts
  frontend/src/screens/Courses/sagas/index.ts
  frontend/src/screens/Courses/services/courses.page.service.ts
  frontend/src/screens/Landing/containers/LandingPage/index.tsx
  frontend/src/screens/PathPage/components/PathOverview/index.tsx
  frontend/src/screens/Paths/components/MyPaths/index.tsx
Labels: enhancement

#241 Hotfix/212 Course tags tab
  backend/core/src/main/java/com/knewless/core/tag/TagService.java
  backend/core/src/main/resources/application.properties
  backend/core/src/test/resources/application.properties
Labels: patch

#240 Fix/login
  frontend/src/screens/Authentication/constants.tsx
Labels: bug

#242 Fix/243 replace spinners with placeholders
  frontend/src/components/placeholder/CourseCardPlaceHolder/index.tsx
  frontend/src/components/placeholder/CourseCardPlaceHolder/rating.sass
  frontend/src/components/placeholder/CourseCardPlaceHolder/styles.module.sass
  frontend/src/components/placeholder/PathCardPlaceHolder/index.tsx
  frontend/src/components/placeholder/PathCardPlaceHolder/styles.module.sass
  frontend/src/screens/AuthorMainPage/components/AuthorCardsSegment/index.tsx
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
  frontend/src/screens/AuthorMainPage/containers/MainPage/reducer.ts
  frontend/src/screens/AuthorMainPage/models/IAuthorMainPageData.ts
  frontend/src/screens/Landing/containers/LandingPage/index.tsx
  frontend/src/screens/MainPage/containers/MainStudentPage/index.tsx
  frontend/src/screens/MainPage/containers/MainStudentPage/reducer.ts
  frontend/src/screens/MainPage/models/IMainStudentPageData.ts
Labels: bug

#243 Feature/250 not found page
  frontend/src/containers/Routing/index.tsx
  frontend/src/screens/History/containers/HistoryPage/index.tsx
  frontend/src/screens/History/containers/HistoryPage/reducer.ts
  frontend/src/screens/NotFound/container/NotFoundPage/index.tsx
  frontend/src/screens/NotFound/container/NotFoundPage/styles.module.sass
Labels: enhancement

#244 Hotfix/312 spinner on courses page
  frontend/src/screens/Courses/containers/CoursesPage/index.tsx
  frontend/src/screens/MainPage/containers/MainStudentPage/index.tsx
Labels: bug

#245 Feature/223 video quality
  backend/core/src/main/java/com/knewless/core/history/HistoryRepository.java
  frontend/src/screens/Authentication/constants.tsx
  frontend/src/screens/LecturePage/containers/Lectures/index.tsx
  frontend/src/screens/LecturePage/containers/Lectures/reducers.tsx
  frontend/src/screens/LecturePage/containers/Lectures/styles.sass
  frontend/src/screens/LecturePage/models/ILecturePageState.ts
  frontend/src/screens/LecturePage/models/ILecturesList.tsx
  frontend/src/screens/LecturePage/routines/index.tsx
Labels: enhancement

#247 Make footer be at the bottom on the history page
  frontend/src/screens/History/containers/HistoryPage/styles.module.sass
Labels: patch

#249 hotfix/not-found-route
  frontend/src/containers/Routing/index.tsx
Labels: bug

#250 Hotfix/310 tags pool for multiple lectures creation
  frontend/src/screens/AddCourse/components/UploadLectureModal/index.tsx
Labels: bug

#251 Put every route into switch for a proper 404 display
  frontend/src/containers/RootRoute/index.tsx
  frontend/src/containers/Routing/index.tsx
  frontend/src/containers/SettingsRoute/index.tsx
Labels: patch

#252 Hotfix/316 author interests displaying
  backend/core/build.gradle
  backend/core/src/main/java/com/knewless/core/author/AuthorMapper.java
  backend/core/src/main/java/com/knewless/core/course/CourseMapper.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureMapper.java
  backend/core/src/main/java/com/knewless/core/path/PathMapper.java
  backend/core/src/main/java/com/knewless/core/student/StudentService.java
  backend/core/src/main/java/com/knewless/core/student/dto/StudentSettingsDto.java
  backend/core/src/main/java/com/knewless/core/student/mapper/StudentMapper.java
  frontend/src/screens/StudentSettings/containers/Settings/index.tsx
  frontend/src/screens/StudentSettings/models/IStudentSettings.ts
Labels: bug

#259 Patch/215 author public page styles
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/authorArticlesList.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/authorCoursesList.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/authorPublicMenu.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/styles.module.sass
Labels: patch

#255 Added BadCredentialsException handler
  backend/core/src/main/java/com/knewless/core/exception/handling/RestExceptionHandler.java
Labels: patch

#253 patch/317-not-found-redesign
  frontend/src/screens/NotFound/container/NotFoundPage/index.tsx
  frontend/src/screens/NotFound/container/NotFoundPage/styles.module.sass
Labels: patch

#260 Patch/not found animation
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/styles.module.sass
  frontend/src/screens/NotFound/container/NotFoundPage/index.tsx
  frontend/src/screens/NotFound/container/NotFoundPage/styles.module.sass
Labels: patch

#254 Patch/318 replace resume with revision
  frontend/src/screens/CoursePage/components/CourseOverview/index.tsx
Labels: patch

#257 Fixed display course progress on student profile
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/history/HistoryRepository.java
Labels: bug

#261 Fix/213 263 after registration bugs
  frontend/src/components/Header/PopupMenu/index.tsx
  frontend/src/components/Header/UserElement/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/containers/AppRouter/index.tsx
  frontend/src/containers/AppRouter/models/IAppRouterState.ts
  frontend/src/containers/AppRouter/reducer.ts
  frontend/src/containers/AppRouter/routines.ts
  frontend/src/containers/AppRouter/sagas.ts
  frontend/src/containers/RootRoute/index.tsx
  frontend/src/containers/Routing/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorInfoBlock/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorInfoBlock/styles.module.sass
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
  frontend/src/screens/AuthorMainPage/containers/MainPage/reducer.ts
  frontend/src/screens/AuthorMainPage/models/IAuthorMainPageData.ts
  frontend/src/screens/AuthorSettings/containers/Settings/sagas.ts
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
  frontend/src/screens/StudentSettings/containers/Settings/sagas.ts
Labels: bug

#263 Feature/201 recommendations
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseProfileDto.java
  backend/core/src/main/java/com/knewless/core/course/model/Level.java
  backend/core/src/main/java/com/knewless/core/path/PathController.java
  backend/core/src/main/java/com/knewless/core/path/PathRepository.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  backend/core/src/main/java/com/knewless/core/student/StudentService.java
  frontend/src/components/AddToFavouritesButton/component/styles.module.sass
  frontend/src/screens/CoursePage/components/CourseOverview/index.tsx
  frontend/src/screens/MainPage/containers/MainStudentPage/sagas.ts
  frontend/src/screens/MainPage/services/main.page.service.ts
Labels: enhancement

#258 Hotfix/142 replace categories with tags
  backend/core/src/main/java/com/knewless/core/category/CategoryRepository.java
  backend/core/src/main/java/com/knewless/core/category/dto/CategoryDto.java
  backend/core/src/main/java/com/knewless/core/category/model/Category.java
  backend/core/src/main/java/com/knewless/core/course/CourseMapper.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/AuthorCourseDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/AuthorCourseQueryResult.java
  backend/core/src/main/java/com/knewless/core/course/dto/AuthorCourseWithTagsDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseProfileDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseQueryResult.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseWithMinutesDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/PublicAuthorCoursesDto.java
  backend/core/src/main/java/com/knewless/core/course/model/Course.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  backend/core/src/main/resources/application.yml
  backend/core/src/main/resources/db/migration/V29__remove_categories_mentions.sql
  esService.put(EsDataType.PATH
  esService.update(EsDataType.PATH
  frontend/src/components/CourseCard/index.tsx
  frontend/src/components/CourseCard/styles.module.sass
  frontend/src/components/CoursePreview/index.tsx
  frontend/src/helpers/placeholder.helper.ts
  frontend/src/screens/AddPath/components/ClickableCourseCard/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/authorCoursesList.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/reducers.tsx
  frontend/src/screens/AuthorPublicPage/models/IAuthorCourse.tsx
  frontend/src/screens/CoursePage/components/CourseOverview/index.tsx
  frontend/src/screens/Landing/containers/LandingPage/index.tsx
  frontend/src/screens/MainPage/containers/MainStudentPage/index.tsx
  frontend/src/screens/MainPage/models/IMainStudentPageState.ts
  frontend/src/screens/StudentPage/components/CompletedCourse/index.tsx
  frontend/src/screens/StudentPage/components/CurrentCourse/index.tsx
  frontend/src/screens/StudentPage/containers/StudentProfilePage/index.tsx
  frontend/src/screens/StudentSettings/containers/Settings/index.tsx
Labels: bug, patch

#269 Hotfix/323 show not found for content paths
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  frontend/src/containers/Routing/index.tsx
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
  frontend/src/screens/CoursePage/containers/CoursePage/reducer.ts
  frontend/src/screens/CoursePage/containers/CoursePage/sagas.ts
  frontend/src/screens/LecturePage/containers/Lectures/index.tsx
  frontend/src/screens/LecturePage/containers/Lectures/sagas.tsx
  frontend/src/screens/PathPage/containers/PathPage/index.tsx
  frontend/src/screens/PathPage/containers/PathPage/reducer.ts
  frontend/src/screens/PathPage/containers/PathPage/sagas.ts
Labels: bug

#270 Hotfix/316 student interests
  frontend/src/screens/StudentSettings/containers/Settings/index.tsx
Labels: bug

#273 Hotfix/326 338 author public page styles
  frontend/src/components/AddToFavouritesButton/component/index.tsx
  frontend/src/components/AddToFavouritesButton/component/styles.module.sass
  frontend/src/components/CourseCard/index.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/authorArticlesList.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/authorCoursesList.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/index.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/styles.module.sass
Labels: bug

#274 Patch/351 tags redesign paths page
  frontend/src/screens/Courses/containers/CoursesPage/styles.module.sass
  frontend/src/screens/Paths/components/AllPaths/index.tsx
  frontend/src/screens/Paths/components/MyPaths/index.tsx
  frontend/src/screens/Paths/containers/PathsPage/index.tsx
  frontend/src/screens/Paths/containers/PathsPage/styles.module.sass
  frontend/src/screens/Paths/models/IPathsData.ts
  frontend/src/screens/Paths/services/paths.service.ts
Labels: patch

#278 Hotfix/347 article page avatar and text
  frontend/src/helpers/placeholder.helper.ts
  frontend/src/screens/AddArticle/containers/AddArticlePage/index.tsx
  frontend/src/screens/ArticlePage/components/ArticleCard/index.tsx
  frontend/src/screens/ArticlePage/components/ArticleCard/styles.module.sass
  frontend/src/screens/ArticlePage/components/AuthorCard/index.tsx
  frontend/src/screens/ArticlePage/components/AuthorCard/styles.module.sass
  frontend/src/screens/ArticlePage/containers/ArticlePage/index.tsx
  frontend/src/screens/ArticlePage/containers/ArticlePage/styles.module.sass
Labels: bug

#279 Hotfix/316 duplicate tags suggestions
  frontend/src/helpers/api.helper.ts
  frontend/src/helpers/validation.helper.ts
  frontend/src/screens/AddCourse/components/UploadLectureModal/index.tsx
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/styles.module.sass
  frontend/src/screens/StudentSettings/containers/Settings/index.tsx
Labels: bug

#280 Feature/201 recommends improvements
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/AuthorCourseQueryResult.java
  backend/core/src/main/java/com/knewless/core/course/dto/AuthorCourseWithTagsDto.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  backend/core/src/main/java/com/knewless/core/security/SecurityConfiguration.java
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/authorCoursesList.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/reducers.tsx
  frontend/src/screens/AuthorPublicPage/models/IAuthorCourse.tsx
  frontend/src/screens/Landing/components/BottomNavigation/index.tsx
  frontend/src/screens/Landing/components/NavigationSection/index.tsx
  frontend/src/screens/Landing/containers/LandingPage/index.tsx
  frontend/src/screens/Landing/containers/LandingPage/sagas.ts
  frontend/src/screens/Landing/services/landing.service.ts
  frontend/src/screens/Landing/services/mock.ts
  frontend/src/screens/LecturePage/containers/Lectures/styles.sass
Labels: bug, enhancement, patch

#281 Patch/160 Replaced LocalDate with ZonedDate for the proper message time display
  backend/core/src/main/java/com/knewless/core/course/courseComment/dto/CourseCommentDto.java
  backend/core/src/main/java/com/knewless/core/lecture/lectureComment/dto/LectureCommentDto.java
Labels: patch

#282 Patch/305 (partially) Improved progress saving when video has ended
  frontend/src/screens/LecturePage/containers/Lectures/index.tsx
Labels: patch

#283 Patch/222 courses paths add button
  frontend/src/helpers/placeholder.helper.ts
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/styles.module.sass
  frontend/src/screens/ArticlePage/components/AuthorCard/index.tsx
  frontend/src/screens/ArticlePage/containers/ArticlePage/index.tsx
  frontend/src/screens/ArticlePage/containers/ArticlePage/sagas.ts
  frontend/src/screens/Courses/components/MyCourses/index.tsx
  frontend/src/screens/Courses/containers/CoursesPage/styles.module.sass
  frontend/src/screens/PathPage/components/AuthorCard/index.tsx
  frontend/src/screens/Paths/components/MyPaths/index.tsx
  frontend/src/screens/Paths/containers/PathsPage/styles.module.sass
Labels: bug, patch

#284 Feature/366 When switching between videos made url change
  frontend/src/screens/LecturePage/containers/Lectures/index.tsx
Labels: enhancement

#285 Patch/353 Fixed styling for toastrs
  frontend/src/styles/toastrStyles.sass
Labels: patch

#286 Patch/354, 365, 376 Fixes on courses and paths pages
  frontend/src/screens/Courses/components/AllCourses/index.tsx
  frontend/src/screens/Paths/components/AllPaths/index.tsx
  frontend/src/screens/Paths/containers/PathsPage/index.tsx
  frontend/src/screens/Paths/containers/PathsPage/reducer.ts
  frontend/src/screens/Paths/containers/PathsPage/sagas.ts
  frontend/src/screens/Paths/containers/PathsPage/styles.module.sass
  frontend/src/screens/Paths/models/IPathsState.ts
  frontend/src/screens/Paths/reducers/index.ts
  frontend/src/screens/Paths/routines/index.ts
Labels: patch

#287 Patch/160 Added flex-grow on add path page
  frontend/src/screens/AddPath/containers/AddPathPage/styles.module.sass
Labels: patch

#288 Patch/286 view all - replace with blue to white underlined (main page author and student)
  frontend/src/components/CardsSegment/styles.module.sass
  frontend/src/components/buttons/common.variables.sass
  frontend/src/screens/AuthorMainPage/components/AuthorCardsSegment/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorCardsSegment/styles.module.sass
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
Labels: patch

#289 Fix/352 login
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  frontend/src/components/Header/PopupMenu/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/containers/AppRouter/index.tsx
  frontend/src/containers/AppRouter/reducer.ts
  frontend/src/screens/Authentication/containers/reducer.tsx
Labels: bug

#293 Fix/154 379 375 315 357 364 378 350 enabling save button course path and attend bugs
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseMapper.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseDetailsDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseDetailsQueryResult.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseQueryResult.java
  backend/core/src/main/java/com/knewless/core/path/PathController.java
  backend/core/src/main/java/com/knewless/core/path/PathMapper.java
  backend/core/src/main/java/com/knewless/core/path/PathRepository.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathCreationRequestDto.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathDetailsDto.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathUpdateRequestDto.java
  backend/core/src/main/java/com/knewless/core/path/dto/PathWithDraftsDto.java
  backend/core/src/main/java/com/knewless/core/path/model/Path.java
  backend/core/src/main/resources/db/migration/V31__paths_add_releaseddate.sql
  frontend/src/components/CoursePreview/index.tsx
  frontend/src/components/CoursePreview/styles.module.sass
  frontend/src/components/Header/PopupMenu/index.tsx
  frontend/src/components/PathCard/index.tsx
  frontend/src/components/PathCard/styles.module.sass
  frontend/src/containers/Routing/index.tsx
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddCourse/containers/AddCoursePage/sagas.ts
  frontend/src/screens/AddCourse/services/add-course.service.ts
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/sagas.ts
  frontend/src/screens/AddPath/containers/AddPathPage/styles.module.sass
  frontend/src/screens/AddPath/models/AddPathState.ts
  frontend/src/screens/AddPath/models/domain.ts
  frontend/src/screens/AddPath/reducers/index.ts
  frontend/src/screens/AddPath/services/add-path.service.ts
  frontend/src/screens/CoursePage/models/IFullCourseData.ts
  frontend/src/screens/CoursePage/models/ILectureData.ts
  frontend/src/screens/Courses/components/MyCourses/index.tsx
  frontend/src/screens/Courses/models/ICourseItem.ts
  frontend/src/screens/PathPage/components/PathOverview/index.tsx
  frontend/src/screens/PathPage/components/PathOverview/styles.module.sass
  frontend/src/screens/PathPage/containers/PathPage/index.tsx
  frontend/src/screens/PathPage/containers/PathPage/reducer.ts
  frontend/src/screens/PathPage/containers/PathPage/sagas.ts
  frontend/src/screens/PathPage/models/IPath.ts
  frontend/src/screens/PathPage/routines/index.ts
  frontend/src/screens/Paths/components/MyPaths/index.tsx
Labels: bug

#292 Fix/372 course description
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/dto/AuthorCourseQueryResult.java
  backend/core/src/main/java/com/knewless/core/course/dto/AuthorCourseWithTagsDto.java
  frontend/src/components/LogoWithText/index.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/authorCoursesList.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/reducers.tsx
  frontend/src/screens/AuthorPublicPage/models/IAuthorCourse.tsx
Labels: enhancement, patch

#291 Patch/344 circle packing chart placeholder
  frontend/src/components/Charts/CirclePackingChart.js
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/index.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/styles.module.sass
  frontend/src/screens/StudentPage/containers/StudentProfilePage/index.tsx
Labels: patch

#294 Feature/343 - Added support for lecture image preview. Formatted code
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/history/WatchHistoryService.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureRepository.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureService.java
  backend/core/src/main/java/com/knewless/core/lecture/dto/LectureDto.java
  backend/core/src/main/java/com/knewless/core/lecture/dto/LectureToPlayerDto.java
  backend/core/src/main/java/com/knewless/core/lecture/dto/ShortLectureDto.java
  backend/core/src/main/java/com/knewless/core/lecture/mapper/LectureProjectionMapper.java
Labels: enhancement

#296 Changed text of a button
  frontend/src/screens/AuthorMainPage/components/AuthorCardsSegment/index.tsx
Labels: patch

#298 Patch/374 small updates
  frontend/src/components/CourseCard/styles.module.sass
  frontend/src/components/CoursePreview/index.tsx
  frontend/src/components/CoursePreview/styles.module.sass
  frontend/src/components/discussion/MessageList/index.tsx
  frontend/src/screens/AddArticle/models/AddArticleData.ts
  frontend/src/screens/ArticlePage/components/ArticleCard/index.tsx
  frontend/src/screens/Favourites/components/lectures/lecture.row.tsx
Labels: patch

#299 Patch/389 Added flex-grow for the path page container
  frontend/src/screens/PathPage/containers/PathPage/styles.module.sass
Labels: patch

#300 Patch/392 display all courses paths tab
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/path/PathController.java
  backend/core/src/main/java/com/knewless/core/path/PathRepository.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  frontend/src/screens/Courses/services/courses.page.service.ts
  frontend/src/screens/Paths/services/paths.service.ts
Labels: patch

#304 Fix/334 361 hide overview make description mandatory
  backend/core/src/main/java/com/knewless/core/author/AuthorService.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureService.java
  frontend/src/components/AddToFavouritesButton/component/styles.module.sass
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/styles.module.sass
  frontend/src/screens/CoursePage/components/CourseOverview/index.tsx
  frontend/src/screens/CoursePage/components/CourseOverview/styles.module.sass
  frontend/src/screens/PathPage/components/PathOverview/styles.module.sass
  frontend/src/screens/PathPage/containers/PathPage/index.tsx
Labels: patch

#306 Patch/240, 241. 348 Fix search
  frontend/src/components/CourseCard/rating.sass
  frontend/src/components/StatefulTagSelector/index.tsx
  frontend/src/components/StyledRating/rating.sass
  frontend/src/components/TagSelector/index.tsx
  frontend/src/components/placeholder/CourseCardPlaceHolder/rating.sass
  frontend/src/screens/SearchResultsPage/components/AdvancedFilter/index.tsx
  frontend/src/screens/SearchResultsPage/components/SearchFeed/index.tsx
  frontend/src/screens/SearchResultsPage/components/SearchFilteringTagSelector/index.tsx
  frontend/src/screens/SearchResultsPage/components/author/Filter/AuthorFilter.tsx
  frontend/src/screens/SearchResultsPage/components/author/Segment/AuthorSegment.tsx
  frontend/src/screens/SearchResultsPage/components/course/Filter/CourseFilter.tsx
  frontend/src/screens/SearchResultsPage/components/course/Segment/CourseSegment.tsx
  frontend/src/screens/SearchResultsPage/components/model.ts
  frontend/src/screens/SearchResultsPage/components/path/Filter/PathFilter.tsx
  frontend/src/screens/SearchResultsPage/components/path/Segment/PathSegment.tsx
  frontend/src/screens/SearchResultsPage/components/school/Filter/SchoolFilter.tsx
  frontend/src/screens/SearchResultsPage/components/school/Segment/SchoolSegment.tsx
  frontend/src/screens/SearchResultsPage/containers/SearchResultsPage/index.tsx
  frontend/src/screens/SearchResultsPage/containers/SearchResultsPage/styles.module.sass
Labels: patch

#307 Added /es/sync api endpoint to sync ES with main storage
  backend/core/src/main/java/com/knewless/core/elasticsearch/DevEsController.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/DevEsService.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/model/EsEntity.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/model/EsMapper.java
Labels: enhancement

#303 Feature/245 followings
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  backend/core/src/main/java/com/knewless/core/student/StudentService.java
  backend/core/src/main/java/com/knewless/core/student/dto/StudentProfileDto.java
  backend/core/src/main/java/com/knewless/core/student/dto/StudentSubscriptionDto.java
  backend/core/src/main/java/com/knewless/core/student/dto/StudentSubscriptionQueryResult.java
  backend/core/src/main/java/com/knewless/core/subscription/SubscriptionRepository.java
  frontend/src/components/StudentFollowCard/index.tsx
  frontend/src/components/StudentFollowCard/styles.module.sass
  frontend/src/components/StudentFollowsModal/index.tsx
  frontend/src/components/StudentFollowsModal/styles.module.sass
  frontend/src/components/discussion/DiscussionBlock/index.tsx
  frontend/src/components/discussion/InputBlock/index.tsx
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/sagas.tsx
  frontend/src/screens/StudentPage/containers/StudentProfilePage/index.tsx
  frontend/src/screens/StudentPage/containers/StudentProfilePage/reducer.ts
  frontend/src/screens/StudentPage/containers/StudentProfilePage/styles.module.sass
  frontend/src/screens/StudentPage/models/IStudentProfile.ts
  frontend/src/screens/StudentPage/routines/index.ts
Labels: enhancement, patch

#309 Hotfix/release edited course path
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/path/PathService.java
  backend/core/src/main/java/com/knewless/core/student/StudentService.java
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
Labels: bug

#308 Patch/240 Sorting. Changed Field mapping, added keyword index for sorting
  backend/core/src/main/java/com/knewless/core/elasticsearch/model/EsEntity.java
Labels: patch

#314 Added mapping for author and course
  backend/core/src/main/java/com/knewless/core/elasticsearch/model/EsMapper.java
  frontend/src/screens/SearchResultsPage/models/EsModels.ts
Labels: patch

#313 Fix/356 video progress
  backend/core/src/main/java/com/knewless/core/history/WatchHistoryService.java
  frontend/src/screens/AuthorMainPage/containers/MainPage/reducer.ts
  frontend/src/screens/LecturePage/containers/Lectures/index.tsx
  frontend/src/screens/MainPage/containers/MainStudentPage/reducer.ts
Labels: bug

#311 Fixed edge cases when image could be too high or too wide
  frontend/src/screens/AddPath/components/ClickableCourseCard/styles.module.sass
Labels: patch

#312 Extracted common logic, handled updatedAt date equals null
  backend/core/src/main/java/com/knewless/core/elasticsearch/model/EsMapper.java
Labels: patch

#316 Fix/418 duplicates
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/EsService.java
Labels: bug

#318 style: course discussion placeholder centered
  frontend/src/components/discussion/MessageList/index.tsx
  frontend/src/components/discussion/MessageList/styles.module.sass
  frontend/src/components/placeholder/ListPlaceholder/index.tsx
Labels: bug

#315 Patch/300 411 Fix page layout, rebuilt author's card layout
  frontend/src/screens/PathPage/components/AboutSection/index.tsx
  frontend/src/screens/PathPage/components/AboutSection/styles.module.sass
  frontend/src/screens/PathPage/components/AuthorCard/index.tsx
  frontend/src/screens/PathPage/components/AuthorCard/styles.module.sass
  frontend/src/screens/PathPage/containers/PathPage/styles.module.sass
Labels: patch

#320 Added width property
  frontend/src/screens/PathPage/components/AboutSection/styles.module.sass
Labels: patch

#321 Feature/254 redesign author card change default lecture image
  backend/core/src/main/java/com/knewless/core/lecture/LectureMapper.java
  frontend/src/assets/images/noVideo.png
  frontend/src/screens/AddCourse/containers/UploadLectureModal/index.tsx
  frontend/src/screens/Favourites/components/courses/course.row.tsx
  frontend/src/screens/Favourites/components/courses/styles.module.sass
  frontend/src/screens/Favourites/components/lectures/lecture.row.tsx
  frontend/src/screens/Favourites/components/lectures/styles.module.sass
  frontend/src/screens/Favourites/components/paths/styles.module.sass
  frontend/src/screens/PathPage/containers/PathPage/index.tsx
  frontend/src/screens/SearchResultsPage/components/author/Card/index.tsx
  frontend/src/screens/SearchResultsPage/components/author/Card/styles.module.sass
  frontend/src/screens/SearchResultsPage/components/author/Segment/AuthorSegment.tsx
  frontend/src/screens/SearchResultsPage/components/author/Segment/styles.module.sass
Labels: patch

#319 Feature/400 favorite articles
  backend/core/src/main/java/com/knewless/core/article/ArticleController.java
  backend/core/src/main/java/com/knewless/core/article/ArticleRepository.java
  backend/core/src/main/java/com/knewless/core/article/ArticleService.java
  backend/core/src/main/java/com/knewless/core/article/dto/ArticleFullDto.java
  backend/core/src/main/java/com/knewless/core/article/dto/FavouriteArticleDto.java
  backend/core/src/main/java/com/knewless/core/favorite/FavoriteController.java
  backend/core/src/main/java/com/knewless/core/favorite/FavoriteService.java
  frontend/src/screens/AddArticle/models/domain.ts
  frontend/src/screens/ArticlePage/containers/ArticlePage/index.tsx
  frontend/src/screens/ArticlePage/containers/ArticlePage/reducer.ts
  frontend/src/screens/ArticlePage/containers/ArticlePage/sagas.ts
  frontend/src/screens/ArticlePage/containers/ArticlePage/styles.module.sass
  frontend/src/screens/ArticlePage/models/ArticleData.ts
  frontend/src/screens/ArticlePage/models/ArticleState.ts
  frontend/src/screens/ArticlePage/models/domain.ts
  frontend/src/screens/ArticlePage/reducers/index.ts
  frontend/src/screens/ArticlePage/routines/index.ts
  frontend/src/screens/ArticlePage/services/article.service.ts
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/sagas.tsx
  frontend/src/screens/CoursePage/services/course.service.ts
  frontend/src/screens/Favourites/components/articles/article.row.tsx
  frontend/src/screens/Favourites/components/articles/index.tsx
  frontend/src/screens/Favourites/components/articles/styles.module.sass
  frontend/src/screens/Favourites/components/lectures/lecture.row.tsx
  frontend/src/screens/Favourites/components/lectures/styles.module.sass
  frontend/src/screens/Favourites/containers/FavouritesPage/index.tsx
  frontend/src/screens/Favourites/containers/FavouritesPage/reducer.ts
  frontend/src/screens/Favourites/containers/FavouritesPage/sagas.ts
  frontend/src/screens/Favourites/containers/FavouritesPage/styles.module.sass
  frontend/src/screens/Favourites/models/IFavouriteData.tsx
  frontend/src/screens/Favourites/models/IFavouriteState.tsx
  frontend/src/screens/Favourites/reducers/index.ts
  frontend/src/screens/Favourites/routines/index.ts
  frontend/src/screens/Favourites/services/favourites.service.ts
  frontend/src/screens/Favourites/services/helper.ts
Labels: enhancement, patch

#324 Added ability to clear all items at ES. Added messages after successful sync or clear
  backend/core/src/main/java/com/knewless/core/elasticsearch/DevEsController.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/DevEsService.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/EsRepository.java
Labels: enhancement

#329 Patch/438 Clear search box when search fired
  frontend/src/screens/Search/containers/SearchHeader/index.tsx
Labels: patch

#330 Patch/Added placeholder when there are no recommended courses or paths
  frontend/src/screens/MainPage/containers/MainStudentPage/index.tsx
Labels: patch

#327 Feature/248 drag n drop
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/CourseLectureDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/CreateCourseRequestDto.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureRepository.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureService.java
  backend/core/src/main/java/com/knewless/core/lecture/dto/LectureDto.java
  backend/core/src/main/java/com/knewless/core/lecture/dto/LectureToPlayerDto.java
  backend/core/src/main/java/com/knewless/core/lecture/dto/ShortLectureDto.java
  backend/core/src/main/java/com/knewless/core/lecture/mapper/LectureProjectionMapper.java
  backend/core/src/main/java/com/knewless/core/lecture/model/Lecture.java
  backend/core/src/main/java/com/knewless/core/path/PathRepository.java
  backend/core/src/main/resources/db/migration/V3__add_lecture_order.sql
  frontend/package.json
  frontend/src/screens/AddCourse/components/AddCourseDependenciesSelector/index.tsx
  frontend/src/screens/AddCourse/components/DragNDropList/index.tsx
  frontend/src/screens/AddCourse/components/DragNDropList/styles.module.sass
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddCourse/models/ICourse.ts
  frontend/src/screens/AddCourse/models/IUpdateCourse.ts
Labels: bug, enhancement

#331 Hotfix/434 path
  backend/core/src/main/java/com/knewless/core/path/PathRepository.java
Labels: bug

#332 Fix/440 drag n drop
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/Articles/components/MyArticles/index.tsx
  frontend/src/screens/Courses/components/MyCourses/index.tsx
  frontend/src/screens/Paths/components/MyPaths/index.tsx
Labels: bug

#335 Patch/286 redesign
  backend/core/src/main/java/com/knewless/core/course/CourseController.java
  backend/core/src/main/java/com/knewless/core/course/CourseMapper.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/course/dto/AuthorCourseDto.java
  backend/core/src/main/java/com/knewless/core/course/dto/AuthorCourseQueryResult.java
  frontend/src/components/PathCard/index.tsx
  frontend/src/components/PathCard/styles.module.sass
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/ArticlePage/containers/ArticlePage/styles.module.sass
  frontend/src/screens/AuthorMainPage/components/AuthorCardsSegment/styles.module.sass
  frontend/src/screens/AuthorMainPage/components/AuthorCourseCard/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorCourseCard/styles.module.sass
  frontend/src/screens/AuthorMainPage/components/AuthorOptionsDropdown/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorOptionsDropdown/styles.module.sass
  frontend/src/screens/AuthorMainPage/containers/MainPage/index.tsx
  frontend/src/screens/AuthorMainPage/containers/MainPage/reducer.ts
  frontend/src/screens/AuthorMainPage/models/IAuthorMainPageData.ts
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/styles.module.sass
Labels: patch

#337 Patch/427 proper redirecting
  frontend/src/components/Header/UserElement/index.tsx
  frontend/src/containers/Notifications/NotificatonItem/index.tsx
  frontend/src/containers/Notifications/NotificatonItem/styles.module.sass
  frontend/src/containers/Notifications/index.tsx
  frontend/src/screens/AddArticle/containers/AddArticlePage/index.tsx
  frontend/src/screens/AddArticle/containers/AddArticlePage/sagas.ts
  frontend/src/screens/AddArticle/services/add-article.service.ts
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddCourse/models/ILecture.ts
  frontend/src/screens/CoursePage/components/CourseInfo/index.tsx
  frontend/src/screens/CoursePage/components/CourseMenu/index.tsx
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
  frontend/src/screens/Favourites/components/lectures/lecture.row.tsx
  frontend/src/screens/Favourites/components/lectures/styles.module.sass
  frontend/src/screens/History/components/HistoryItem/index.tsx
  frontend/src/screens/LecturePage/containers/Lectures/index.tsx
  frontend/src/screens/LecturePage/containers/Lectures/lecturesMenu.tsx
Labels: bug, patch

#338 Fix/340 markdown
  frontend/src/components/ArticlePreview/styles.module.sass
  frontend/src/components/OverviewModal/styles.module.sass
  frontend/src/screens/ArticlePage/containers/ArticlePage/styles.module.sass
Labels: patch

#339 Patch/286, 446 Fix button text wrap
  frontend/src/screens/AuthorMainPage/components/AuthorCardsSegment/index.tsx
  frontend/src/screens/AuthorMainPage/components/AuthorCardsSegment/styles.module.sass
Labels: patch

#340 hotfix/447-empty-about-author
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/index.tsx
Labels: bug

#341 Fixed bug when no notifications
  frontend/src/containers/Notifications/index.tsx
Labels: patch

#342 Hotfix/431 path save toastr messages
  frontend/src/screens/AddPath/containers/AddPathPage/index.tsx
  frontend/src/screens/AddPath/containers/AddPathPage/sagas.ts
Labels: bug

#343 Fix/442 too much text article card
  frontend/src/components/ArticlePreview/index.tsx
  frontend/src/containers/Notifications/NotificatonItem/index.tsx
  frontend/src/screens/ArticlePage/containers/ArticlePage/index.tsx
  frontend/src/screens/CoursePage/components/CourseMenu/index.tsx
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
Labels: bug

#344 Hotfix/417 too big button
  frontend/src/screens/PathPage/components/PathOverview/index.tsx
  frontend/src/screens/PathPage/components/PathOverview/styles.module.sass
  frontend/src/screens/PathPage/containers/PathPage/index.tsx
Labels: bug

#345 feat: add tag loading at course preview
  backend/core/src/main/java/com/knewless/core/course/CourseService.java
  backend/core/src/main/java/com/knewless/core/elasticsearch/EsService.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureMapper.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureRepository.java
  backend/core/src/main/java/com/knewless/core/lecture/LectureService.java
  backend/core/src/main/java/com/knewless/core/lecture/dto/ShortLectureDto.java
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AddCourse/models/ILecture.ts
  frontend/src/screens/CoursePage/models/ILectureData.ts
Labels: bug

#346 fix: add tag image message in path creation
  backend/core/src/main/java/com/knewless/core/path/PathService.java
Labels: bug

#348 Fix/401 author image
  backend/core/src/main/java/com/knewless/core/author/AuthorService.java
  frontend/src/helpers/validation.helper.ts
  frontend/src/screens/AuthorSettings/containers/Settings/index.tsx
  frontend/src/screens/AuthorSettings/containers/Settings/reducer.ts
  frontend/src/screens/StudentSettings/containers/Settings/reducer.ts
Labels: bug

#347 Feature/395 personal goal notification
  backend/core/src/main/java/com/knewless/core/dailyProgress/DailyProgressController.java
  backend/core/src/main/java/com/knewless/core/db/SourceType.java
  backend/core/src/main/java/com/knewless/core/history/WatchHistoryService.java
  backend/core/src/main/java/com/knewless/core/notification/NotificationRepository.java
  backend/core/src/main/java/com/knewless/core/notification/NotificationService.java
  backend/core/src/main/java/com/knewless/core/progressGoal/ProgressGoalService.java
  backend/core/src/main/java/com/knewless/core/progressGoal/dto/ProgressGoalBriefDto.java
  backend/core/src/main/java/com/knewless/core/student/StudentController.java
  backend/core/src/main/java/com/knewless/core/student/StudentGoalProgressService.java
  backend/core/src/main/java/com/knewless/core/student/StudentService.java
  backend/core/src/main/java/com/knewless/core/student/dto/ProgressResponseDto.java
  backend/core/src/main/java/com/knewless/core/student/model/Student.java
  backend/core/src/main/java/com/knewless/core/user/UserRepository.java
  backend/core/src/main/resources/db/migration/V5__completed_goal_last_shown.sql
  frontend/package.json
  frontend/src/containers/Notifications/NotificatonItem/index.tsx
  frontend/src/helpers/seconds.helper.ts
  frontend/src/screens/MainPage/containers/ConfettiCannon/index.tsx
  frontend/src/screens/MainPage/containers/CongratulationsAnimation/animation.sass
  frontend/src/screens/MainPage/containers/CongratulationsAnimation/index.tsx
  frontend/src/screens/MainPage/containers/MainStudentPage/sagas.ts
  frontend/src/screens/MainPage/containers/UserInfoBlock/index.tsx
  frontend/src/screens/MainPage/containers/UserInfoBlock/styles.module.sass
  frontend/src/screens/MainPage/models/PersonalGoal.ts
  frontend/src/screens/MainPage/routines/index.ts
  frontend/src/screens/MainPage/services/main.page.service.ts
Labels: enhancement

#353 Fix/450 logout redirect
  frontend/src/components/Header/PopupMenu/index.tsx
  frontend/src/containers/LoginModal/reducer.ts
Labels: bug

#350 Patch/History page time format
  frontend/src/containers/Notifications/NotificatonItem/index.tsx
  frontend/src/screens/History/components/HistoryItem/index.tsx
Labels: patch

#351 Hotfix/451 article card description overflow
  frontend/src/components/ArticlePreview/index.tsx
  frontend/src/components/ArticlePreview/styles.module.sass
  frontend/src/screens/Articles/components/MyArticles/index.tsx
  frontend/src/screens/Articles/containers/ArticlesPage/index.tsx
Labels: bug

#352 Fix/327 388 course card overflow bugs
  frontend/src/components/CoursePreview/index.tsx
  frontend/src/components/CoursePreview/styles.module.sass
Labels: bug

#356 Hotfix/296 course preview description
  esService.put(EsDataType.PATH
  esService.update(EsDataType.PATH
  frontend/src/components/CoursePreview/index.tsx
  frontend/src/components/CoursePreview/styles.module.sass
  frontend/src/screens/AddCourse/containers/AddCoursePage/index.tsx
  frontend/src/screens/AuthorSettings/containers/Settings/index.tsx
  frontend/src/screens/AuthorSettings/containers/Settings/options.tsx
Labels: bug

#355 Hotfix/452 number of students on course preview
  backend/core/src/main/java/com/knewless/core/article/mapper/ArticleMapper.java
  backend/core/src/main/java/com/knewless/core/author/AuthorService.java
  backend/core/src/main/java/com/knewless/core/author/mapper/AuthorInfoMapper.java
  backend/core/src/main/java/com/knewless/core/author/mapper/OldAuthorMapper.java
  backend/core/src/main/java/com/knewless/core/course/CourseRepository.java
  backend/core/src/main/java/com/knewless/core/course/dto/AuthorCourseWithTagsDto.java
  frontend/src/screens/AuthorPublicPage/containers/AuthorPublicPage/authorCoursesList.tsx
  frontend/src/screens/AuthorPublicPage/models/IAuthorCourse.tsx
Labels: bug

#354 fix: courses links work on course page
  frontend/src/screens/CoursePage/containers/CoursePage/index.tsx
Labels: bug

#357 Fix/362 empty profile while paths loading
  frontend/src/components/CoursePreview/styles.module.sass
  frontend/src/screens/Paths/components/MyPaths/index.tsx
  frontend/src/screens/Paths/containers/PathsPage/index.tsx
  frontend/src/screens/Paths/containers/PathsPage/reducer.ts
  frontend/src/screens/Paths/models/IPathsData.ts
Labels: bug

#358 Added async, improved logging
  backend/fileprocessor/src/main/java/fileprocessor/Application.java
  backend/fileprocessor/src/main/java/fileprocessor/lecture/model/Lecture.java
  backend/fileprocessor/src/main/java/fileprocessor/notification/NotificationService.java
  backend/fileprocessor/src/main/java/fileprocessor/videoencoder/VideoEncoderService.java
  backend/fileprocessor/src/main/resources/application.properties
Labels: enhancement

#362 hotfix/455-author-course-query-mapping
  backend/core/src/main/java/com/knewless/core/course/CourseMapper.java
Labels: bug

#361 Fixed undefined when the lecture was just uploaded and tags selected
  backend/core/src/main/java/com/knewless/core/lecture/LectureService.java
Labels: patch

#359 Added youtube preview parsing, Simplified code
  backend/core/src/main/java/com/knewless/core/lecture/LectureService.java
  backend/core/src/main/java/com/knewless/core/youtube/YoutubeHelper.java
Labels: enhancement

#360 Hotfix/Handle ws subscription when no connection established (not logged in)
  frontend/src/containers/discussions/CourseDiscussion/index.tsx
  frontend/src/containers/discussions/LectureDiscussion/index.tsx
Labels: patch

#365 Patch/454 Handle tags overflow on course card
  frontend/src/components/CoursePreview/styles.module.sass
Labels: patch

#366 Patch/458 misc bugs
  backend/core/src/main/java/com/knewless/core/lecture/LectureService.java
  frontend/src/screens/CoursePage/components/CourseMenu/index.tsx
  frontend/src/screens/Favourites/components/lectures/styles.module.sass
  frontend/src/screens/PathPage/components/AuthorCard/index.tsx
  frontend/src/screens/PathPage/components/AuthorCard/styles.module.sass
  frontend/src/screens/PathPage/components/PathOverview/index.tsx
Labels: patch

#368 Hotfix/458 Check if preview image exists before invoking it's methods
  backend/core/src/main/java/com/knewless/core/lecture/LectureService.java
Labels: patch
